import React, { createContext, useContext, useState, useEffect } from 'react';

export const LANGUAGES = [
  { code: 'ta', label: 'தமிழ்', name: 'Tamil', flag: '🇮🇳' },
  { code: 'en', label: 'English', name: 'English', flag: '🇬🇧' },
  { code: 'hi', label: 'हिंदी', name: 'Hindi', flag: '🇮🇳' },
  { code: 'te', label: 'తెలుగు', name: 'Telugu', flag: '🇮🇳' },
  { code: 'kn', label: 'ಕನ್ನಡ', name: 'Kannada', flag: '🇮🇳' },
  { code: 'ml', label: 'മലയാളം', name: 'Malayalam', flag: '🇮🇳' }
];

export const TRANSLATIONS = {
  // ==========================================
  // 1. TAMIL (தமிழ்)
  // ==========================================
  ta: {
    // Header & Navigation
    homepot_chef: 'ஹோம்பாட் செஃப்',
    homepot_kitchen: 'ஹோம்பாட் சமையலறை',
    partner_portal: 'அம்மாக்கள் & இல்லத்தரசிகள் சமையல் தளம்',
    manage_live_orders: 'நேரடி ஆர்டர்கள் & தினசரி மெனுவை நிர்வகிக்கவும்',
    cook_with_love: 'பாசத்துடன் சமைப்போம் • பெருமையுடன் ஈட்டுவோம்',
    kitchen_open: 'சமையலறை திறந்துள்ளது',
    kitchen_closed: 'சமையலறை மூடப்பட்டுள்ளது',
    tap_to_change: 'மாற்ற தொடவும்',
    live_orders: 'நேரடி ஆர்டர்கள்',
    menu: 'உணவு மெனு',
    bankings: 'வங்கி கணக்கு',
    profile: 'சுயவிவரம்',
    notifications: 'அறிவிப்புகள்',
    help_support: 'உதவி & ஆதரவு',
    settings: 'அமைப்புகள்',
    choose_language: 'மொழியை மாற்றுக',

    // Live Orders
    live_orders_subtitle: 'உள்வரும் வாடிக்கையாளர் ஆர்டர்களை உடனுக்குடன் நிர்வகிக்கவும்',
    active: 'செயலில்',
    no_orders_queued: 'தற்போது புதிய ஆர்டர்கள் எதுவும் இல்லை. வாடிக்கையாளர்கள் ஆர்டர் செய்தவுடன் தானாகவே இங்கு தோன்றும்!',
    status_new_order: 'புதிய ஆர்டர்',
    status_preparing: 'சமைக்கப்படுகிறது',
    status_ready: 'எடுக்க தயார்',
    status_completed: 'முடிந்தது',
    status_rejected: 'நிராகரிக்கப்பட்டது',
    accept_order_btn: 'ஆர்டரை ஏற்கவும்',
    reject_order_btn: 'நிராகரி',
    mark_ready_btn: 'உணவு தயார் என குறிக்கவும்',
    complete_order_btn: 'ஆர்டரை முடிக்கவும்',
    dishes_label: 'உணவுகள்:',
    just_now: 'சற்று முன்',
    enter_rejection_reason: 'நிராகரிப்பதற்கான காரணத்தை உள்ளிடவும் (எ.கா. தீர்ந்துவிட்டது / சமையலறை மூடல்):',

    // Onboarding / Login / Signup
    chef_portal: 'அம்மாக்கள் & இல்லத்தரசிகள் சமையல் தளம்',
    authentic_tagline: 'வீட்டு சுவையில் பாசத்துடன் தயாராகும் உணவுகள்',
    sign_in: 'செஃப் உள்நுழைவு',
    sign_up: 'புதிய செஃப் பதிவு',
    chef_email_address: 'செஃப் மின்னஞ்சல் முகவரி',
    email_address: 'மின்னஞ்சல் முகவரி',
    password: 'கடவுச்சொல்',
    mobile_number: 'கைபேசி எண்',
    set_password: 'புதிய கடவுச்சொல்',
    send_otp: 'சரிபார்ப்பு குறியீடு அனுப்பவும் (OTP)',
    enter_otp: '4 இலக்க குறியீட்டை உள்ளிடவும்',
    verify_proceed: 'குறியீட்டை சரிபார்த்து தொடரவும்',
    resend_code: 'மறுபடி குறியீடு அனுப்பு',
    already_chef: 'ஏற்கனவே பதிந்துள்ளீர்களா?',
    new_chef_prompt: 'புதிய சமையல் கலைஞரா?',
    register_kitchen: 'சமையலறை பதிவு செய்க',
    signing_in: 'உள்நுழைகிறது...',
    sending_otp: 'குறியீடு அனுப்பப்படுகிறது...',
    verify_otp_title: 'OTP சரிபார்க்கவும்',
    verify_otp_subtitle: 'உங்கள் கைபேசி & மின்னஞ்சலுக்கு வந்த 4 இலக்க குறியீட்டை உள்ளிடவும்',
    verify_and_continue: 'சரிபார்த்து சமையலறை விவரங்களுக்கு செல்லவும்',
    change_email_mobile: '← மின்னஞ்சல் அல்லது கைபேசி எண்ணை மாற்றவும்',

    // Kitchen Registration (Step 2)
    step_2_title: 'படி 2 / 3 • சமையலறை & சுகாதாரம்',
    amma_chef_photo: 'புகைப்படம் பதிவேற்றவும் (Upload Photo)',
    kitchen_name: 'சமையலறை பெயர்',
    kitchen_name_placeholder: 'உதா., அம்மா சமையல் கூடம்',
    owner_full_name: 'உரிமையாளர் முழு பெயர்',
    owner_name_placeholder: 'உங்கள் பெயரை உள்ளிடவும்',
    fssai_title: 'FSSAI பதிவு / உணவு பாதுகாப்பு சான்றிதழ்',
    fssai_placeholder: '14 இலக்க FSSAI எண்',
    fssai_verified: 'அரசு API சரிபார்க்கப்பட்டது',
    fssai_verifying: 'FoSCoS அரசு தளத்துடன் இணைகிறது...',
    kitchen_address: 'சமையலறை முகவரி & இடம்',
    kitchen_address_placeholder: 'கதவு எண், தெரு பெயர், பகுதி, ஊர்',
    privacy_shield: 'செஃப் பாதுகாப்பு: முகவரி வாடிக்கையாளருக்கு உணவு எடுக்கும் நேரத்தில் மட்டுமே காட்டப்படும்.',
    cuisine_specialties: 'சமையல் வகைகள் (பொருந்துவதை தேர்வு செய்யவும்)',
    pure_veg: 'சுத்த சைவ உணவு',
    south_indian: 'தென்னிந்திய உணவு',
    north_indian: 'வடஇந்திய உணவு',
    home_sweets: 'வீட்டு இனிப்பு & பலகாரங்கள்',
    andhra_style: 'ஆந்திரா காரசார உணவு',
    safety_declaration_title: 'உணவு பாதுகாப்பு & நியாய விலை உறுதிமொழி:',
    safety_declaration_desc: 'வீட்டு சமையலறையில் சுத்தமாகவும், ஆரோக்கியமான முறையிலும், நியாயமான விலையிலும் உணவு தயாரித்து வழங்குவேன் என உறுதியளிக்கிறேன்.',
    continue_to_banking: 'வங்கி விவரங்களுக்கு செல்லவும்',

    // Banking Setup (Step 3)
    banking_title: 'வங்கி கணக்கு & பணப்பட்டுவாடா',
    step_3_title: 'படி 3 / 3 • வாராந்திர நேரடி பணப்பட்டுவாடா',
    account_holder: 'கணக்கு வைத்திருப்பவர் பெயர்',
    account_holder_placeholder: 'வங்கி பாஸ்புக்கில் உள்ளபடி பெயர்',
    bank_name: 'வங்கி பெயர்',
    bank_name_placeholder: 'உதா., இந்தியன் வங்கி, SBI, HDFC',
    account_number: 'வங்கி கணக்கு எண்',
    ifsc_code: 'IFSC குறியீடு',
    upi_id: 'UPI முகவரி (விரைவு பரிவர்த்தனைக்கு)',
    upi_placeholder: 'உதா., peyar@okaxis',
    direct_payout_title: '100% நேரடி பணப்பட்டுவாடா உத்தரவாதம்',
    direct_payout_desc: 'உங்கள் வாராந்திர உழைப்பின் வருமானம் நேரடியாக உங்கள் வங்கிக் கணக்கில் எந்த கமிஷன் பிடித்தமும் இன்றி வந்து சேரும்.',
    open_kitchen_btn: 'சமையலறையை திறந்து ஆர்டர்களை தொடங்கவும்',
    back_to_kitchen_btn: 'சமையலறை விவரங்களுக்கு திரும்பவும்',

    // Bankings Page in Dashboard
    available_balance: 'கிடைக்கக்கூடிய இருப்பு',
    secure_payouts: 'பாதுகாப்பான பணப்பட்டுவாடா',
    pending_settlement: 'நிலுவையில் உள்ள தொகை',
    available_in_24h: '24 மணி நேரத்தில் கிடைக்கும்',
    withdraw_instantly: 'உடனடியாக வங்கியில் எடுக்கவும்',
    transferring: 'பணம் அனுப்பப்படுகிறது...',
    total_earnings: 'மொத்த வருமானம்',
    lifetime_revenue: 'இதுவரை ஈட்டிய மொத்த வருவாய்',
    active_mode: 'செயலில் உள்ள முறை',
    linked: 'இணைக்கப்பட்டுள்ளது',
    not_linked: 'இணைக்கப்படவில்லை',
    upi_active: 'UPI செயலில் உள்ளது',
    bank_active: 'வங்கி செயலில் உள்ளது',
    setup_required: 'அமைவு தேவை',
    payout_destination: 'பணம் சேரும் இடம்',
    upi_id_tab: 'UPI முகவரி',
    bank_account_tab: 'வங்கி கணக்கு',
    primary_upi_id: 'முக்கிய UPI முகவரி',
    edit_upi: 'UPI மாற்றுக',
    enter_upi_id: 'UPI முகவரியை உள்ளிடவும்',
    save_upi: 'UPI சேமிக்கவும்',
    change_ac: 'வங்கி கணக்கு மாற்றுக',
    penny_drop_note: 'வங்கி கணக்கு விவரங்கள் உடனடி சரிபார்ப்பு மூலம் உறுதி செய்யப்படும்.',
    name_as_per_bank: 'வங்கி பதிவேட்டில் உள்ளபடி பெயர்',
    enter_ac_digits: '9 முதல் 18 இலக்க கணக்கு எண்ணை உள்ளிடவும்',
    verifying_bank: 'வங்கியுடன் சரிபார்க்கப்படுகிறது...',
    verify_save_ac: 'சரிபார்த்து கணக்கை சேமிக்கவும்',
    recent_payouts_orders: 'சமீபத்திய பணப்பரிவர்த்தனைகள் & ஆர்டர்கள்',
    last_30_days: 'கடந்த 30 நாட்கள்',
    no_transactions_yet: 'இதுவரை பரிவர்த்தனைகள் எதுவும் இல்லை',
    transactions_desc: 'உங்கள் ஆர்டர்கள் மற்றும் பணம் எடுப்புகள் இங்கு தோன்றும்.',

    // Profile Page in Dashboard
    open: 'திறந்துள்ளது',
    closed: 'மூடப்பட்டுள்ளது',
    share_kitchen_prompt: 'வாடிக்கையாளர்கள் உங்கள் சமையலறையை பார்க்க வேண்டுமா?',
    share_profile_btn: 'சுயவிவர இணைப்பை பகிரவும்',
    link_copied: 'இணைப்பு நகலெடுக்கப்பட்டது! ✓',
    kitchen_profile_details: 'சமையலறை சுயவிவர விவரங்கள்',
    edit_profile: 'விவரங்களை திருத்தவும்',
    cancel: 'ரத்து',
    save_changes: 'மாற்றங்களை சேமிக்கவும்',
    location_landmark: 'இடம் / அடையாளம்',
    phone_number_label: 'கைபேசி எண்',
    email_address_label: 'மின்னஞ்சல் முகவரி',
    chef_bio: 'செஃப் சுயவிவரம்',
    instagram_handle: 'இன்ஸ்டாகிராம் / சமூக ஊடகம்',
    change_profile_picture: 'சுயவிவரப் படத்தை மாற்றவும்',
    chef_name: 'செஃப் பெயர்',
    customer_reviews_title: 'வாடிக்கையாளர் மதிப்புரைகள் & மதிப்பீடுகள்',
    overall_rating: 'ஒட்டுமொத்த மதிப்பீடு:',
    reviews_count: 'மதிப்புரைகள்',
    chef_dashboard_badge: 'செஃப் கட்டுப்பாட்டு தளம்',
    no_reviews_yet: 'இதுவரை மதிப்புரைகள் எதுவும் வரவில்லை. ஆர்டர்கள் செல்லும்போது வாடிக்கையாளர்கள் கருத்து வழங்குவார்கள்!',
    profile_updated_success: 'சுயவிவரம் மற்றும் இடம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',

    // Modals
    no_notifications_yet: 'புதிய ஆர்டர் அறிவிப்புகள் எதுவும் இல்லை.',
    close: 'மூடு',
    got_it: 'புரிந்தது',
    push_notifications: 'புஷ் அறிவிப்புகள்',
    receive_alerts: 'புதிய ஆர்டர்களுக்கான விழிப்பூட்டல்களைப் பெறுங்கள்',
    auto_accept_orders: 'தானியங்கி ஆர்டர் ஏற்பு',
    auto_accept_desc: 'தயார் நிலையில் உள்ள நேரங்களை தானாக ஏற்கவும்',
    log_out: 'வெளியேறு',
    delete_account: 'கணக்கை நீக்கு',
    save_close: 'சேமித்து மூடுக',
    delete_account_warning: 'இந்த செயல் உங்கள் சுயவிவரம், மெனு மற்றும் வருமான விவரங்களை நிரந்தரமாக நீக்கும்.',
    send_verification_otp: 'சரிபார்ப்பு OTP அனுப்பு',
    verify_permanently_delete: 'சரிபார்த்து நிரந்தரமாக நீக்கு',

    // Menu & Daily Hygiene
    daily_hygiene_required: 'இன்றைய சமையலறை புகைப்படம் தேவை',
    daily_hygiene_desc: 'ஆர்டர்கள் தொடங்கும் முன், உங்கள் சுத்தமான சமையல் மேடையை கேமராவில் படம் எடுத்து பகிரவும்.',
    daily_hygiene_verified: 'இன்றைய சமையலறை சுகாதாரம் சரிபார்க்கப்பட்டது',
    daily_hygiene_verified_desc: 'இன்று நேரடி கேமராவில் படம் எடுக்கப்பட்டது. வாடிக்கையாளர்கள் இதை பார்க்க முடியும்!',
    open_camera_btn: 'கேமராவை திறந்து படம் எடுக்கவும்',
    retake_camera_btn: 'மீண்டும் கேமரா படம் எடுக்கவும்',
    direct_camera_btn: 'நேரடி கேமரா',
    live_view: 'நேரடி பார்வை',
    point_camera_tip: 'கேமராவை சுத்தமான சமையல் மேடையை நோக்கி வைத்து பட்டனை அழுத்தவும்.',

    menu_portions_title: 'சமையலறை மெனு & அளவுகள்',
    menu_portions_subtitle: 'உணவை சேர்க்கவும், மாற்றவும், அளவுகளை சரிசெய்யவும்',
    add_dish_btn: 'உணவு சேர்க்க',
    portions_label: 'அளவுகள்:',
    edit_btn: 'திருத்து',
    mark_sold_out: 'தீர்ந்துவிட்டது என குறிக்கவும்',
    mark_available: 'உள்ளது என குறிக்கவும்',
    available_badge: 'உள்ளது',
    sold_out_badge: 'தீர்ந்துவிட்டது',
    add_signature_dish: 'சிறப்பு வீட்டு உணவை சேர்க்க',
    edit_dish_title: 'உணவு விவரங்களை திருத்தவும்',
    dish_photo_optional: 'உணவு புகைப்படம் (விருப்பப்பட்டால்)',
    upload_photo: 'படம் பதிவேற்ற',
    change_photo: 'படம் மாற்ற',
    remove_photo: 'நீக்கு',
    dish_name_label: 'உணவின் பெயர்',
    dish_name_placeholder: 'உதா., நெய் மசால் தோசை / சாம்பார் சாதம்',
    meal_slot_label: 'உணவு நேரம்',
    breakfast: 'காலை உணவு',
    lunch: 'மதிய உணவு',
    dinner: 'இரவு உணவு',
    snacks: 'மாலை பலகாரங்கள் & இனிப்பு',
    food_type_label: 'உணவு வகை',
    price_per_plate: 'ஒரு தட்டு விலை (₹)',
    daily_portions_label: 'இன்றைய அளவுகள் (எண்ணிக்கை)',
    description_label: 'உணவு விளக்கம் & மூலப்பொருட்கள்',
    description_placeholder: 'வீட்டு முறையில் தயாராகும் மூலப்பொருட்களை விவரிக்கவும்...',
    save_dish_btn: 'சேமித்து மெனுவில் சேர்க்க',
    update_dish_btn: 'மாற்றங்களை சேமிக்கவும்',
    empty_menu_title: 'உங்கள் மெனு காலியாக உள்ளது.',
    empty_menu_desc: 'மேலே உள்ள "+ உணவு சேர்க்க" பட்டனை அழுத்தி உங்கள் முதல் உணவை சேர்க்கவும்!'
  },

  // ==========================================
  // 2. ENGLISH (en)
  // ==========================================
  en: {
    homepot_chef: 'HomePot Chef',
    homepot_kitchen: 'HomePot Kitchen',
    partner_portal: 'Partner Portal for Home Chefs',
    manage_live_orders: 'Manage Live Orders & Daily Menus',
    cook_with_love: 'Cook with Love • Earn with Pride',
    kitchen_open: 'Kitchen OPEN',
    kitchen_closed: 'Kitchen CLOSED',
    tap_to_change: 'Tap to switch',
    live_orders: 'Live Orders',
    menu: 'Menu',
    bankings: 'Bankings',
    profile: 'Profile',
    notifications: 'Notifications',
    help_support: 'Help & Support',
    settings: 'Settings',
    choose_language: 'Change Language',

    live_orders_subtitle: 'Manage incoming customer requests in real-time',
    active: 'Active',
    no_orders_queued: 'No new orders queued right now. Incoming customer orders will appear here automatically!',
    status_new_order: 'New Order',
    status_preparing: 'Preparing',
    status_ready: 'Ready for Pickup',
    status_completed: 'Completed',
    status_rejected: 'Rejected',
    accept_order_btn: 'Accept Order',
    reject_order_btn: 'Reject',
    mark_ready_btn: 'Mark as Ready for Pickup',
    complete_order_btn: 'Complete Order',
    dishes_label: 'Dishes:',
    just_now: 'Just now',
    enter_rejection_reason: 'Please enter reason for rejection (e.g. Sold out / Kitchen closing):',

    chef_portal: 'Mother & Homemaker Chef Portal',
    authentic_tagline: 'Authentic home-cooked meals prepared with love',
    sign_in: 'Chef Sign In',
    sign_up: 'New Chef Sign Up',
    chef_email_address: 'Chef Email Address',
    email_address: 'Email Address',
    password: 'Password',
    mobile_number: 'Mobile Number',
    set_password: 'Set Password',
    send_otp: 'Send 4-Digit OTP',
    enter_otp: 'Enter 4-Digit OTP',
    verify_proceed: 'Verify & Proceed',
    resend_code: 'Resend Code',
    already_chef: 'Already registered?',
    new_chef_prompt: 'New Chef?',
    register_kitchen: 'Register Your Kitchen',
    signing_in: 'Signing In...',
    sending_otp: 'Sending OTP...',
    verify_otp_title: 'Verify OTP',
    verify_otp_subtitle: 'Enter the 4-digit code sent to your mobile & email',
    verify_and_continue: 'Verify & Continue to Kitchen Details',
    change_email_mobile: '← Change email or mobile number',

    step_2_title: 'Step 2 / 3 • Kitchen & Hygiene',
    amma_chef_photo: 'Upload Photo',
    kitchen_name: 'Kitchen Name',
    kitchen_name_placeholder: 'e.g. Amma Home Kitchen',
    owner_full_name: 'Owner Full Name',
    owner_name_placeholder: 'Enter your full legal name',
    fssai_title: 'FSSAI Registration / Food Safety License',
    fssai_placeholder: '14-digit FSSAI Number',
    fssai_verified: 'Government API Verified',
    fssai_verifying: 'Connecting to FoSCoS Government Portal...',
    kitchen_address: 'Kitchen Address & Location',
    kitchen_address_placeholder: 'Flat/Door No., Street Name, Area, City',
    privacy_shield: 'Chef Privacy: Address is only shared with customer upon order pickup.',
    cuisine_specialties: 'Cuisine Specialties (Select applicable)',
    pure_veg: 'Pure Vegetarian',
    south_indian: 'South Indian',
    north_indian: 'North Indian',
    home_sweets: 'Homemade Sweets & Snacks',
    andhra_style: 'Spicy Andhra Style',
    safety_declaration_title: 'Food Hygiene & Fair Pricing Pledge:',
    safety_declaration_desc: 'I pledge to cook with authentic hygiene, fresh ingredients, and honest portions directly from my home.',
    continue_to_banking: 'Continue to Banking Details',

    banking_title: 'Bank Account & Payouts',
    step_3_title: 'Step 3 / 3 • Weekly Direct Payouts',
    account_holder: 'Account Holder Name',
    account_holder_placeholder: 'Name as printed on bank passbook',
    bank_name: 'Bank Name',
    bank_name_placeholder: 'e.g. Indian Bank, SBI, HDFC',
    account_number: 'Bank Account Number',
    ifsc_code: 'IFSC Code',
    upi_id: 'UPI ID (For instant settlements)',
    upi_placeholder: 'e.g. name@okhdfcbank',
    direct_payout_title: '100% Direct Payout Guarantee',
    direct_payout_desc: 'Your weekly earnings go directly to your personal bank account with zero commission cuts.',
    open_kitchen_btn: 'Open Kitchen & Start Receiving Orders',
    back_to_kitchen_btn: 'Back to Kitchen Details',

    available_balance: 'Available Balance',
    secure_payouts: 'Secure Payouts',
    pending_settlement: 'Pending settlement',
    available_in_24h: 'Available in 24 hours',
    withdraw_instantly: 'Withdraw Instantly',
    transferring: 'Transferring...',
    total_earnings: 'Total Earnings',
    lifetime_revenue: 'Lifetime revenue',
    active_mode: 'Active Mode',
    linked: 'Linked',
    not_linked: 'Not Linked',
    upi_active: 'UPI Active',
    bank_active: 'Bank Active',
    setup_required: 'Setup Required',
    payout_destination: 'Payout Destination',
    upi_id_tab: 'UPI ID',
    bank_account_tab: 'Bank Account',
    primary_upi_id: 'Primary UPI ID',
    edit_upi: 'Edit UPI',
    enter_upi_id: 'Enter UPI ID',
    save_upi: 'Save UPI',
    change_ac: 'Change A/C',
    penny_drop_note: 'Account details are verified instantly via penny-drop against banking gateways.',
    name_as_per_bank: 'Name as per bank records',
    enter_ac_digits: 'Enter 9 to 18 digit account number',
    verifying_bank: 'Verifying with Bank...',
    verify_save_ac: 'Verify & Save Account',
    recent_payouts_orders: 'Recent Payouts & Orders',
    last_30_days: 'Last 30 Days',
    no_transactions_yet: 'No transactions yet',
    transactions_desc: 'Your orders and withdrawals will appear here.',

    open: 'OPEN',
    closed: 'CLOSED',
    share_kitchen_prompt: 'Want customers to find your kitchen?',
    share_profile_btn: 'Share Profile Link',
    link_copied: 'Link Copied! ✓',
    kitchen_profile_details: 'Kitchen Profile Details',
    edit_profile: 'Edit Profile',
    cancel: 'Cancel',
    save_changes: 'Save Changes',
    location_landmark: 'Location / Landmark',
    phone_number_label: 'Phone Number',
    email_address_label: 'Email Address',
    chef_bio: 'Chef Bio',
    instagram_handle: 'Instagram / Social Handle',
    change_profile_picture: 'Change Profile Picture',
    chef_name: 'Chef Name',
    customer_reviews_title: 'Customer Reviews & Ratings',
    overall_rating: 'Overall Rating:',
    reviews_count: 'reviews',
    chef_dashboard_badge: 'Chef Dashboard',
    no_reviews_yet: 'No reviews from customers yet. Share your profile link to start receiving feedback!',
    profile_updated_success: 'Profile and location updated successfully!',

    no_notifications_yet: 'No new order notifications yet.',
    close: 'Close',
    got_it: 'Got It',
    push_notifications: 'Push Notifications',
    receive_alerts: 'Receive alerts for new orders',
    auto_accept_orders: 'Auto-Accept Orders',
    auto_accept_desc: 'Automatically accept ready slots',
    log_out: 'Log Out',
    delete_account: 'Delete Account',
    save_close: 'Save & Close',
    delete_account_warning: 'This action is permanent and will delete all your chef profile data, menu lists, and earnings history.',
    send_verification_otp: 'Send Verification OTP',
    verify_permanently_delete: 'Verify & Permanently Delete',

    daily_hygiene_required: 'Daily Kitchen Photo Required',
    daily_hygiene_desc: 'Before starting live orders, take a real-time camera photo of your clean kitchen counter.',
    daily_hygiene_verified: "Today's Kitchen Hygiene Verified",
    daily_hygiene_verified_desc: 'Captured via live camera today. Customers can view this on your profile!',
    open_camera_btn: 'Open Camera & Capture Counter',
    retake_camera_btn: 'Retake Camera Photo',
    direct_camera_btn: 'Live Camera',
    live_view: 'Live View',
    point_camera_tip: 'Point camera at your clean cooking counter and press Capture.',

    menu_portions_title: 'Kitchen Menu & Portions',
    menu_portions_subtitle: 'Add dishes, update meal slots, and manage available daily portions',
    add_dish_btn: 'Add Dish',
    portions_label: 'Portions:',
    edit_btn: 'Edit',
    mark_sold_out: 'Mark Sold Out',
    mark_available: 'Mark Available',
    available_badge: 'Available',
    sold_out_badge: 'Sold Out',
    add_signature_dish: 'Add Signature Home Dish',
    edit_dish_title: 'Edit Dish Details',
    dish_photo_optional: 'Dish Photo (Optional)',
    upload_photo: 'Upload Photo',
    change_photo: 'Change Photo',
    remove_photo: 'Remove',
    dish_name_label: 'Dish Name',
    dish_name_placeholder: 'e.g. Ghee Masala Dosa / Sambar Rice',
    meal_slot_label: 'Meal Slot',
    breakfast: 'Breakfast',
    lunch: 'Lunch',
    dinner: 'Dinner',
    snacks: 'Evening Snacks & Sweets',
    food_type_label: 'Food Type',
    price_per_plate: 'Price per Plate (₹)',
    daily_portions_label: 'Daily Portions Count',
    description_label: 'Dish Description & Ingredients',
    description_placeholder: 'Describe your authentic preparation style...',
    save_dish_btn: 'Save & Add to Menu',
    update_dish_btn: 'Save Changes',
    empty_menu_title: 'Your menu is empty right now.',
    empty_menu_desc: 'Tap "+ Add Dish" above to create your very first authentic home meal!'
  },

  // ==========================================
  // 3. HINDI (हिंदी)
  // ==========================================
  hi: {
    homepot_chef: 'होमपॉट शेफ',
    homepot_kitchen: 'होमपॉट किचन',
    partner_portal: 'गृहणियों और शेफ्स का अपना मंच',
    manage_live_orders: 'लाइव ऑर्डर्स और दैनिक मेनू प्रबंधित करें',
    cook_with_love: 'प्यार से पकाएं • गर्व से कमाएं',
    kitchen_open: 'किचन खुला है',
    kitchen_closed: 'किचन बंद है',
    tap_to_change: 'बदलने के लिए टैप करें',
    live_orders: 'लाइव ऑर्डर्स',
    menu: 'भोजन मेनू',
    bankings: 'बैंक खाता',
    profile: 'प्रोफाइल',
    notifications: 'सूचनाएं',
    help_support: 'मदद और सहायता',
    settings: 'सेटिंग्स',
    choose_language: 'भाषा बदलें',

    live_orders_subtitle: 'ग्राहकों के नए ऑर्डर्स को तुरंत स्वीकारें और प्रबंधित करें',
    active: 'सक्रिय',
    no_orders_queued: 'वर्तमान में कोई नया ऑर्डर नहीं है। ग्राहक द्वारा ऑर्डर करते ही यहां दिखाई देगा!',
    status_new_order: 'नया ऑर्डर',
    status_preparing: 'तैयार हो रहा है',
    status_ready: 'पिकअप के लिए तैयार',
    status_completed: 'पूर्ण हुआ',
    status_rejected: 'अस्वीकृत',
    accept_order_btn: 'ऑर्डर स्वीकार करें',
    reject_order_btn: 'अस्वीकार करें',
    mark_ready_btn: 'भोजन तैयार चिह्नित करें',
    complete_order_btn: 'ऑर्डर पूरा करें',
    dishes_label: 'व्यंजन:',
    just_now: 'अभी-अभी',
    enter_rejection_reason: 'अस्वीकार करने का कारण दर्ज करें:',

    chef_portal: 'गृहणियों और शेफ्स का अपना मंच',
    authentic_tagline: 'घर के स्वाद और प्यार से बना शुद्ध भोजन',
    sign_in: 'शेफ लॉगिन',
    sign_up: 'नया शेफ पंजीकरण',
    chef_email_address: 'शेफ ईमेल पता',
    email_address: 'ईमेल पता',
    password: 'पासवर्ड',
    mobile_number: 'मोबाइल नंबर',
    set_password: 'नया पासवर्ड बनाएं',
    send_otp: '4-अंकीय OTP भेजें',
    enter_otp: '4-अंकीय OTP दर्ज करें',
    verify_proceed: 'सत्यापित करें और आगे बढ़ें',
    resend_code: 'दोबारा कोड भेजें',
    already_chef: 'क्या पहले से पंजीकृत हैं?',
    new_chef_prompt: 'नए शेफ हैं?',
    register_kitchen: 'अपना किचन पंजीकृत करें',
    signing_in: 'लॉगिन हो रहा है...',
    sending_otp: 'OTP भेजा जा रहा है...',
    verify_otp_title: 'OTP सत्यापित करें',
    verify_otp_subtitle: 'अपने मोबाइल और ईमेल पर भेजा गया 4-अंकीय कोड दर्ज करें',
    verify_and_continue: 'सत्यापित करें और किचन विवरण भरें',
    change_email_mobile: '← ईमेल या मोबाइल नंबर बदलें',

    step_2_title: 'चरण 2 / 3 • रसोई और स्वच्छता',
    amma_chef_photo: 'फोटो अपलोड करें (Upload Photo)',
    kitchen_name: 'किचन का नाम',
    kitchen_name_placeholder: 'उदा., माँ की रसोई',
    owner_full_name: 'मालिक का पूरा नाम',
    owner_name_placeholder: 'अपना पूरा नाम दर्ज करें',
    fssai_title: 'FSSAI पंजीकरण / खाद्य सुरक्षा नंबर',
    fssai_placeholder: '14 अंकों का FSSAI नंबर',
    fssai_verified: 'सरकारी API सत्यापित',
    fssai_verifying: 'FoSCoS पोर्टल से जुड़ रहा है...',
    kitchen_address: 'किचन का पता और स्थान',
    kitchen_address_placeholder: 'मकान नंबर, गली, क्षेत्र, शहर',
    privacy_shield: 'शेफ सुरक्षा: पता केवल ऑर्डर पिकअप के समय ग्राहक को दिखाया जाता है।',
    cuisine_specialties: 'विशेषताएं (चुनें जो लागू हों)',
    pure_veg: 'शुद्ध शाकाहारी',
    south_indian: 'दक्षिण भारतीय',
    north_indian: 'उत्तर भारतीय',
    home_sweets: 'घर की बनी मिठाइयाँ और नाश्ता',
    andhra_style: 'आंध्र मसालेदार भोजन',
    safety_declaration_title: 'स्वच्छता और उचित मूल्य प्रतिज्ञा:',
    safety_declaration_desc: 'मैं अपने घर की रसोई से शुद्धता, स्वच्छता और उचित मात्रा में भोजन तैयार करने का संकल्प लेता/लेती हूँ।',
    continue_to_banking: 'बैंक विवरण पर आगे बढ़ें',

    banking_title: 'बैंक खाता और भुगतान',
    step_3_title: 'चरण 3 / 3 • साप्ताहिक सीधा भुगतान',
    account_holder: 'खाताधारक का नाम',
    account_holder_placeholder: 'बैंक पासबुक के अनुसार नाम',
    bank_name: 'बैंक का नाम',
    bank_name_placeholder: 'उदा., SBI, HDFC, PNB',
    account_number: 'बैंक खाता संख्या',
    ifsc_code: 'IFSC कोड',
    upi_id: 'UPI आईडी (तुरंत भुगतान हेतु)',
    upi_placeholder: 'उदा., naam@okaxis',
    direct_payout_title: '100% सीधे बैंक भुगतान की गारंटी',
    direct_payout_desc: 'आपकी साप्ताहिक कमाई बिना किसी कटौती के सीधे आपके बैंक खाते में भेजी जाती है।',
    open_kitchen_btn: 'किचन खोलें और ऑर्डर्स शुरू करें',
    back_to_kitchen_btn: 'किचन विवरण पर वापस जाएं',

    available_balance: 'उपलब्ध शेष राशि',
    secure_payouts: 'सुरक्षित भुगतान',
    pending_settlement: 'लंबित निपटान राशि',
    available_in_24h: '24 घंटे में उपलब्ध',
    withdraw_instantly: 'तुरंत बैंक में ट्रांसफर करें',
    transferring: 'पैसे ट्रांसफर हो रहे हैं...',
    total_earnings: 'कुल कमाई',
    lifetime_revenue: 'अब तक की कुल कमाई',
    active_mode: 'सक्रिय मोड',
    linked: 'लिंक किया गया',
    not_linked: 'लिंक नहीं है',
    upi_active: 'UPI सक्रिय है',
    bank_active: 'बैंक सक्रिय है',
    setup_required: 'सेटअप आवश्यक है',
    payout_destination: 'भुगतान गंतव्य',
    upi_id_tab: 'UPI आईडी',
    bank_account_tab: 'बैंक खाता',
    primary_upi_id: 'प्राथमिक UPI आईडी',
    edit_upi: 'UPI बदलें',
    enter_upi_id: 'UPI आईडी दर्ज करें',
    save_upi: 'UPI सहेजें',
    change_ac: 'बैंक खाता बदलें',
    penny_drop_note: 'बैंक खाता तुरंत सुरक्षित बैंकिंग गेटवे के माध्यम से सत्यापित किया जाता है।',
    name_as_per_bank: 'बैंक रिकॉर्ड के अनुसार नाम',
    enter_ac_digits: '9 से 18 अंकों का खाता नंबर दर्ज करें',
    verifying_bank: 'बैंक से सत्यापित हो रहा है...',
    verify_save_ac: 'सत्यापित करें और खाता सहेजें',
    recent_payouts_orders: 'हाल के भुगतान और ऑर्डर्स',
    last_30_days: 'पिछले 30 दिन',
    no_transactions_yet: 'अभी तक कोई लेनदेन नहीं हुआ है',
    transactions_desc: 'आपके ऑर्डर्स और निकासी का विवरण यहाँ दिखाई देगा।',

    open: 'खुला है',
    closed: 'बंद है',
    share_kitchen_prompt: 'क्या आप चाहते हैं कि ग्राहक आपका किचन देखें?',
    share_profile_btn: 'प्रोफाइल लिंक साझा करें',
    link_copied: 'लिंक कॉपी हो गया! ✓',
    kitchen_profile_details: 'किचन प्रोफाइल विवरण',
    edit_profile: 'प्रोफाइल संपादित करें',
    cancel: 'रद्द करें',
    save_changes: 'परिवर्तन सहेजें',
    location_landmark: 'स्थान / लैंडमार्क',
    phone_number_label: 'फ़ोन नंबर',
    email_address_label: 'ईमेल पता',
    chef_bio: 'शेफ बायो',
    instagram_handle: 'इंस्टाग्राम / सोशल हैंडल',
    change_profile_picture: 'प्रोफाइल फोटो बदलें',
    chef_name: 'शेफ का नाम',
    customer_reviews_title: 'ग्राहक समीक्षाएं और रेटिंग',
    overall_rating: 'समग्र रेटिंग:',
    reviews_count: 'समीक्षाएं',
    chef_dashboard_badge: 'शेफ डैशबोर्ड',
    no_reviews_yet: 'अभी तक कोई ग्राहक समीक्षा नहीं आई है।',
    profile_updated_success: 'प्रोफाइल और स्थान सफलतापूर्वक अपडेट किया गया!',

    no_notifications_yet: 'कोई नया नोटिफिकेशन नहीं है।',
    close: 'बंद करें',
    got_it: 'समझ गया',
    push_notifications: 'पुश नोटिफिकेशन',
    receive_alerts: 'नए ऑर्डर्स के लिए अलर्ट प्राप्त करें',
    auto_accept_orders: 'ऑटो-स्वीकार ऑर्डर्स',
    auto_accept_desc: 'तैयार स्लॉट्स को स्वतः स्वीकार करें',
    log_out: 'लॉग आउट',
    delete_account: 'खाता हटाएं',
    save_close: 'सहेजें और बंद करें',
    delete_account_warning: 'यह क्रिया स्थायी है और आपके सभी प्रोफाइल डेटा, मेनू और कमाई को हटा देगी।',
    send_verification_otp: 'सत्यापन OTP भेजें',
    verify_permanently_delete: 'सत्यापित करें और स्थायी रूप से हटाएं',

    daily_hygiene_required: 'दैनिक रसोई फोटो आवश्यक है',
    daily_hygiene_desc: 'ऑर्डर शुरू करने से पहले, अपने स्वच्छ कुकिंग काउंटर की लाइव कैमरा फोटो लें।',
    daily_hygiene_verified: 'आज की रसोई स्वच्छता सत्यापित',
    daily_hygiene_verified_desc: 'आज लाइव कैमरे द्वारा खींची गई। ग्राहक इसे आपकी प्रोफाइल पर देख सकते हैं!',
    open_camera_btn: 'कैमरा खोलें और फोटो लें',
    retake_camera_btn: 'दोबारा फोटो लें',
    direct_camera_btn: 'लाइव कैमरा',
    live_view: 'लाइव दृश्य',
    point_camera_tip: 'कैमरे को साफ कुकिंग काउंटर की ओर रखें और कैप्चर दबाएं।',

    menu_portions_title: 'रसोई मेनू और मात्रा',
    menu_portions_subtitle: 'व्यंजन जोड़ें, स्लॉट अपडेट करें और दैनिक मात्रा प्रबंधित करें',
    add_dish_btn: 'व्यंजन जोड़ें',
    portions_label: 'मात्रा:',
    edit_btn: 'संपादित करें',
    mark_sold_out: 'समाप्त चिह्नित करें',
    mark_available: 'उपलब्ध चिह्नित करें',
    available_badge: 'उपलब्ध',
    sold_out_badge: 'समाप्त',
    add_signature_dish: 'खास घरेलू व्यंजन जोड़ें',
    edit_dish_title: 'व्यंजन का विवरण संपादित करें',
    dish_photo_optional: 'व्यंजन फोटो (वैकल्पिक)',
    upload_photo: 'फोटो अपलोड करें',
    change_photo: 'फोटो बदलें',
    remove_photo: 'हटाएं',
    dish_name_label: 'व्यंजन का नाम',
    dish_name_placeholder: 'उदा., घी मसाला डोसा / सांभर चावल',
    meal_slot_label: 'भोजन समय',
    breakfast: 'नाश्ता',
    lunch: 'दोपहर का भोजन',
    dinner: 'रात का भोजन',
    snacks: 'शाम का नाश्ता और मिठाई',
    food_type_label: 'भोजन का प्रकार',
    price_per_plate: 'प्रति प्लेट मूल्य (₹)',
    daily_portions_label: 'दैनिक उपलब्ध मात्रा',
    description_label: 'व्यंजन विवरण और सामग्री',
    description_placeholder: 'घर की पारंपरिक तैयारी का वर्णन करें...',
    save_dish_btn: 'सहेजें और मेनू में जोड़ें',
    update_dish_btn: 'परिवर्तन सहेजें',
    empty_menu_title: 'आपका मेनू अभी खाली है।',
    empty_menu_desc: 'अपना पहला स्वादिष्ट घरेलू भोजन जोड़ने के लिए ऊपर "+ व्यंजन जोड़ें" दबाएं!'
  },

  // ==========================================
  // 4. TELUGU (తెలుగు)
  // ==========================================
  te: {
    homepot_chef: 'హోమ్‌పాట్ చెఫ్',
    homepot_kitchen: 'హోమ్‌పాట్ కిచెన్',
    partner_portal: 'ఇంటి చెఫ్‌ల ప్రత్యేక వేదిక',
    manage_live_orders: 'లైవ్ ఆర్డర్లు మరియు రోజువారీ మెనూ నిర్వహించండి',
    cook_with_love: 'ప్రేమతో వండండి • గర్వంగా సంపాదించండి',
    kitchen_open: 'కిచెన్ తెరిచి ఉంది',
    kitchen_closed: 'కిచెన్ మూసివేయబడింది',
    tap_to_change: 'మార్చడానికి నొక్కండి',
    live_orders: 'లైవ్ ఆర్డర్లు',
    menu: 'ఆహార మెనూ',
    bankings: 'బ్యాంకు ఖాతా',
    profile: 'ప్రొఫైల్',
    notifications: 'నోటిఫికేషన్లు',
    help_support: 'సహాయం & మద్దతు',
    settings: 'సెట్టింగ్‌లు',
    choose_language: 'భాష మార్చండి',

    live_orders_subtitle: 'కస్టమర్ ఆర్డర్‌లను తక్షణమే నిర్వహించండి',
    active: 'యాక్టివ్',
    no_orders_queued: 'ప్రస్తుతం కొత్త ఆర్డర్లు లేవు. కస్టమర్ ఆర్డర్ చేయగానే ఇక్కడ కనిపిస్తుంది!',
    status_new_order: 'కొత్త ఆర్డర్',
    status_preparing: 'వండబడుతోంది',
    status_ready: 'పికప్‌కు సిద్ధం',
    status_completed: 'పూర్తయింది',
    status_rejected: 'తిరస్కరించబడింది',
    accept_order_btn: 'ఆర్డర్ స్వీకరించండి',
    reject_order_btn: 'తిరస్కరించు',
    mark_ready_btn: 'ఆహారం సిద్ధంగా ఉంది అని గుర్తించు',
    complete_order_btn: 'ఆర్డర్ పూర్తి చేయండి',
    dishes_label: 'వంటకాలు:',
    just_now: 'ఇప్పుడే',
    enter_rejection_reason: 'తిరస్కరణకు కారణాన్ని నమోదు చేయండి:',

    chef_portal: 'ఇంటి చెఫ్‌ల ప్రత్యేక వేదిక',
    authentic_tagline: 'ఇంటి రుచితో స్వచ్ఛంగా తయారయ్యే ఆహారం',
    sign_in: 'చెఫ్ లాగిన్',
    sign_up: 'కొత్త చెఫ్ నమోదు',
    chef_email_address: 'చెఫ్ ఈమెయిల్ చిరునామా',
    email_address: 'ఈమెయిల్ చిరునామా',
    password: 'పాస్‌వర్డ్',
    mobile_number: 'మొబైల్ నంబర్',
    set_password: 'కొత్త పాస్‌వర్డ్',
    send_otp: '4 అంకెల OTP పంపండి',
    enter_otp: '4 అంకెల OTP నమోదు చేయండి',
    verify_proceed: 'ధృవీకరించి కొనసాగండి',
    resend_code: 'మళ్లీ కోడ్ పంపు',
    already_chef: 'ఇప్పటికే నమోదయ్యారా?',
    new_chef_prompt: 'కొత్త చెఫ్ ఆ?',
    register_kitchen: 'మీ కిచెన్‌ను నమోదు చేయండి',
    signing_in: 'లాగిన్ అవుతోంది...',
    sending_otp: 'OTP పంపబడుతోంది...',
    verify_otp_title: 'OTP ధృవీకరించండి',
    verify_otp_subtitle: 'మీ మొబైల్ & ఈమెయిల్‌కు పంపిన 4 అంకెల కోడ్‌ను నమోదు చేయండి',
    verify_and_continue: 'ధృవీకరించి కిచెన్ వివరాలకు వెళ్లండి',
    change_email_mobile: '← ఈమెయిల్ లేదా మొబైల్ మార్చండి',

    step_2_title: 'దశ 2 / 3 • వంటగది & పరిశుభ్రత',
    amma_chef_photo: 'ఫోటో అప్‌లోడ్ చేయండి (Upload Photo)',
    kitchen_name: 'కిచెన్ పేరు',
    kitchen_name_placeholder: 'ఉదా., అమ్మ చేతి వంట',
    owner_full_name: 'యజమాని పూర్తి పేరు',
    owner_name_placeholder: 'మీ పేరు నమోదు చేయండి',
    fssai_title: 'FSSAI రిజిస్ట్రేషన్ / ఆహార భద్రతా సంఖ్య',
    fssai_placeholder: '14 అంకెల FSSAI నంబర్',
    fssai_verified: 'ప్రభుత్వ API ధృవీకరించబడింది',
    fssai_verifying: 'FoSCoS ప్రభుత్వ పోర్టల్‌తో అనుసంధానిస్తోంది...',
    kitchen_address: 'కిచెన్ చిరునామా & ప్రాంతం',
    kitchen_address_placeholder: 'డోర్ నం., వీధి, ప్రాంతం, ఊరు',
    privacy_shield: 'చెఫ్ భద్రత: ఆహారం పికప్ సమయంలో మాత్రమే కస్టమర్‌కు చిరునామా చూపబడుతుంది.',
    cuisine_specialties: 'వంటల రకాలు (వర్తించేవి ఎంచుకోండి)',
    pure_veg: 'స్వచ్ఛమైన శాకాహారం',
    south_indian: 'దక్షిణ భారతీయ',
    north_indian: 'ఉత్తర భారతీయ',
    home_sweets: 'ఇంటి స్వీట్లు & పిండివంటలు',
    andhra_style: 'ఘాటైన ఆంధ్ర స్టైల్',
    safety_declaration_title: 'ఆహార పరిశుభ్రత & సరసమైన ధరల వాగ్దానం:',
    safety_declaration_desc: 'పరిశుభ్రమైన వాతావరణంలో, తాజా పదార్థాలతో ఇంటి వంట తయారుచేస్తానని హామీ ఇస్తున్నాను.',
    continue_to_banking: 'బ్యాంకు వివరాలకు వెళ్లండి',

    banking_title: 'బ్యాంకు ఖాతా & చెల్లింపులు',
    step_3_title: 'దశ 3 / 3 • వారపు ప్రత్యక్ష చెల్లింపులు',
    account_holder: 'ఖాతాదారుని పేరు',
    account_holder_placeholder: 'బ్యాంకు పాస్‌బుక్ ప్రకారం పేరు',
    bank_name: 'బ్యాంకు పేరు',
    bank_name_placeholder: 'ఉదా., ఆంధ్ర బ్యాంక్, SBI, HDFC',
    account_number: 'బ్యాంకు ఖాతా సంఖ్య',
    ifsc_code: 'IFSC కోడ్',
    upi_id: 'UPI ఐడీ (తక్షణ చెల్లింపుల కోసం)',
    upi_placeholder: 'ఉదా., peru@okaxis',
    direct_payout_title: '100% ప్రత్యక్ష బ్యాంకు చెల్లింపు గ్యారెంటీ',
    direct_payout_desc: 'మీ వారపు సంపాదన ఎటువంటి కమీషన్ కోత లేకుండా నేరుగా మీ బ్యాంకు ఖాతాకు చేరుతుంది.',
    open_kitchen_btn: 'కిచెన్ ప్రారంభించి ఆర్డర్లు పొందండి',
    back_to_kitchen_btn: 'కిచెన్ వివరాలకు తిరిగి వెళ్లండి',

    available_balance: 'అందుబాటులో ఉన్న నిల్వ',
    secure_payouts: 'సురక్షిత చెల్లింపులు',
    pending_settlement: 'పెండింగ్ మొత్తం',
    available_in_24h: '24 గంటల్లో అందుబాటులో ఉంటుంది',
    withdraw_instantly: 'వెంటనే బ్యాంకుకు బదిలీ చేయండి',
    transferring: 'బదిలీ అవుతోంది...',
    total_earnings: 'మొత్తం ఆదాయం',
    lifetime_revenue: 'ఇప్పటివరకు వచ్చిన మొత్తం ఆదాయం',
    active_mode: 'యాక్టివ్ మోడ్',
    linked: 'లింక్ చేయబడింది',
    not_linked: 'లింక్ కాలేదు',
    upi_active: 'UPI యాక్టివ్‌గా ఉంది',
    bank_active: 'బ్యాంకు యాక్టివ్‌గా ఉంది',
    setup_required: 'సెటప్ అవసరం',
    payout_destination: 'చెల్లింపు గమ్యం',
    upi_id_tab: 'UPI ఐడీ',
    bank_account_tab: 'బ్యాంకు ఖాతా',
    primary_upi_id: 'ప్రధాన UPI ఐడీ',
    edit_upi: 'UPI సవరించండి',
    enter_upi_id: 'UPI ఐడీని నమోదు చేయండి',
    save_upi: 'UPI భద్రపరచండి',
    change_ac: 'ఖాతా మార్చండి',
    penny_drop_note: 'బ్యాంకు ఖాతా వివరాలు తక్షణమే బ్యాంకింగ్ గేట్‌వేల ద్వారా ధృవీకరించబడతాయి.',
    name_as_per_bank: 'బ్యాంకు రికార్డుల ప్రకారం పేరు',
    enter_ac_digits: '9 నుండి 18 అంకెల ఖాతా సంఖ్యను నమోదు చేయండి',
    verifying_bank: 'బ్యాంకుతో ధృవీకరిస్తోంది...',
    verify_save_ac: 'ధృవీకరించి ఖాతాను భద్రపరచండి',
    recent_payouts_orders: 'ఇటీవలి చెల్లింపులు & ఆర్డర్లు',
    last_30_days: 'గత 30 రోజులు',
    no_transactions_yet: 'ఇంకా ఎటువంటి లావాదేవీలు లేవు',
    transactions_desc: 'మీ ఆర్డర్లు మరియు నగదు ఉపసంహరణల వివరాలు ఇక్కడ కనిపిస్తాయి.',

    open: 'తెరిచి ఉంది',
    closed: 'మూసివేయబడింది',
    share_kitchen_prompt: 'కస్టమర్లు మీ వంటగదిని చూడాలనుకుంటున్నారా?',
    share_profile_btn: 'ప్రొఫైల్ లింక్ షేర్ చేయండి',
    link_copied: 'లింక్ కాపీ అయింది! ✓',
    kitchen_profile_details: 'కిచెన్ ప్రొఫైల్ వివరాలు',
    edit_profile: 'సవరించండి',
    cancel: 'రద్దు',
    save_changes: 'మార్పులను భద్రపరచండి',
    location_landmark: 'ప్రాంతం / ల్యాండ్‌మార్క్',
    phone_number_label: 'ఫోన్ నంబర్',
    email_address_label: 'ఈమెయిల్ చిరునామా',
    chef_bio: 'చెఫ్ బయో',
    instagram_handle: 'ఇన్‌స్టాగ్రామ్ / సోషల్ హ్యాండిల్',
    change_profile_picture: 'ప్రొఫైల్ ఫోటో మార్చండి',
    chef_name: 'చెఫ్ పేరు',
    customer_reviews_title: 'కస్టమర్ సమీక్షలు & రేటింగ్‌లు',
    overall_rating: 'మొత్తం రేటింగ్:',
    reviews_count: 'సమీక్షలు',
    chef_dashboard_badge: 'చెఫ్ డ్యాష్‌బోర్డ్',
    no_reviews_yet: 'ఇంకా కస్టమర్ సమీక్షలు రాలేదు.',
    profile_updated_success: 'ప్రొఫైల్ మరియు చిరునామా విజయవంతంగా నవీకరించబడింది!',

    no_notifications_yet: 'కొత్త నోటిఫికేషన్లు లేవు.',
    close: 'మూసివేయి',
    got_it: 'అర్థమైంది',
    push_notifications: 'పుష్ నోటిఫికేషన్లు',
    receive_alerts: 'కొత్త ఆర్డర్ల కోసం హెచ్చరికలను పొందండి',
    auto_accept_orders: 'ఆటో-యాక్సెప్ట్ ఆర్డర్లు',
    auto_accept_desc: 'సిద్ధంగా ఉన్న స్లాట్లను స్వయంచాలకంగా అంగీకరించండి',
    log_out: 'లాగ్ అవుట్',
    delete_account: 'ఖాతాను తొలగించండి',
    save_close: 'భద్రపరచి మూసివేయి',
    delete_account_warning: 'ఈ చర్య మీ మొత్తం డేటాను శాశ్వతంగా తొలగిస్తుంది.',
    send_verification_otp: 'ధృవీకరణ OTP పంపండి',
    verify_permanently_delete: 'ధృవీకరించి శాశ్వతంగా తొలగించండి',

    daily_hygiene_required: 'రోజువారీ వంటగది ఫోటో అవసరం',
    daily_hygiene_desc: 'ఆర్డర్లు ప్రారంభించే ముందు శుభ్రమైన వంటగది కౌంటర్‌ను కెమెరాలో తీయండి.',
    daily_hygiene_verified: 'నేటి వంటగది పరిశుభ్రత ధృవీకరించబడింది',
    daily_hygiene_verified_desc: 'నేడు లైవ్ కెమెరా ద్వారా తీయబడింది. కస్టమర్లు దీనిని చూడగలరు!',
    open_camera_btn: 'కెమెరా తెరిచి ఫోటో తీయండి',
    retake_camera_btn: 'మళ్లీ ఫోటో తీయండి',
    direct_camera_btn: 'లైవ్ కెమెరా',
    live_view: 'లైవ్ వీక్షణ',
    point_camera_tip: 'కెమెరాను శుభ్రమైన కౌంటర్ వైపు ఉంచి క్యాప్చర్ నొక్కండి.',

    menu_portions_title: 'వంటల మెనూ & కొలతలు',
    menu_portions_subtitle: 'వంటకాలు జోడించండి మరియు పరిమాణాలను నిర్వహించండి',
    add_dish_btn: 'వంటకం జోడించండి',
    portions_label: 'కొలతలు:',
    edit_btn: 'సవరించు',
    mark_sold_out: 'అయిపోయిందని గుర్తించు',
    mark_available: 'అందుబాటులో ఉందని గుర్తించు',
    available_badge: 'అందుబాటులో ఉంది',
    sold_out_badge: 'అయిపోయింది',
    add_signature_dish: 'ప్రత్యేక ఇంటి వంటకం జోడించండి',
    edit_dish_title: 'వంటకం వివరాలను సవరించండి',
    dish_photo_optional: 'వంటకం ఫోటో (ఐచ్ఛికం)',
    upload_photo: 'ఫోటో అప్‌లోడ్ చేయండి',
    change_photo: 'ఫోటో మార్చండి',
    remove_photo: 'తొలగించు',
    dish_name_label: 'వంటకం పేరు',
    dish_name_placeholder: 'ఉదా., నెయ్యి మసాలా దోశ / సాంబార్ అన్నం',
    meal_slot_label: 'భోజన సమయం',
    breakfast: 'అల్పాహారం',
    lunch: 'మధ్యాహ్న భోజనం',
    dinner: 'రాత్రి భోజనం',
    snacks: 'సాయంత్రం స్నాక్స్ & స్వీట్స్',
    food_type_label: 'ఆహార రకం',
    price_per_plate: 'ప్లేట్ ధర (₹)',
    daily_portions_label: 'రోజువారీ పరిమాణం',
    description_label: 'వివరణ & పదార్థాలు',
    description_placeholder: 'ఇంటి పద్ధతిలో తయారయ్యే విధానాన్ని వివరించండి...',
    save_dish_btn: 'మెనూలో జోడించండి',
    update_dish_btn: 'మార్పులను భద్రపరచండి',
    empty_menu_title: 'మీ మెనూ ప్రస్తుతం ఖాళీగా ఉంది.',
    empty_menu_desc: 'పైనున్న "+ వంటకం జోడించండి" నొక్కి మీ మొదటి ఇంటి వంటకాన్ని సృష్టించండి!'
  },

  // ==========================================
  // 5. KANNADA (ಕನ್ನಡ)
  // ==========================================
  kn: {
    homepot_chef: 'ಹೋಮ್‌ಪಾಟ್ ಚೆಫ್',
    homepot_kitchen: 'ಹೋಮ್‌ಪಾಟ್ ಅಡುಗೆಮನೆ',
    partner_portal: 'ಮನೆ ಅಡುಗೆಯವರ ಹೆಮ್ಮೆಯ ವೇದಿಕೆ',
    manage_live_orders: 'ಲೈವ್ ಆರ್ಡರ್‌ಗಳು ಮತ್ತು ದೈನಂದಿನ ಮೆನುವನ್ನು ನಿರ್ವಹಿಸಿ',
    cook_with_love: 'ಪ್ರೀತಿಯಿಂದ ಅಡುಗೆ ಮಾಡಿ • ಹೆಮ್ಮೆಯಿಂದ ಸಂಪಾದಿಸಿ',
    kitchen_open: 'ಅಡುಗೆಮನೆ ತೆರೆದಿದೆ',
    kitchen_closed: 'ಅಡುಗೆಮನೆ ಮುಚ್ಚಿದೆ',
    tap_to_change: 'ಬದಲಾಯಿಸಲು ಟ್ಯಾಪ್ ಮಾಡಿ',
    live_orders: 'ಲೈವ್ ಆರ್ಡರ್‌ಗಳು',
    menu: 'ಆಹಾರ ಮೆನು',
    bankings: 'ಬ್ಯಾಂಕ್ ಖಾತೆ',
    profile: 'ಪ್ರೊಫೈಲ್',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    help_support: 'ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    choose_language: 'ಭಾಷೆ ಬದಲಾಯಿಸಿ',

    live_orders_subtitle: 'ಗ್ರಾಹಕರ ಹೊಸ ಆರ್ಡರ್‌ಗಳನ್ನು ತಕ್ಷಣ ನಿರ್ವಹಿಸಿ',
    active: 'ಸಕ್ರಿಯ',
    no_orders_queued: 'ಪ್ರಸ್ತುತ ಹೊಸ ಆರ್ಡರ್‌ಗಳಿಲ್ಲ. ಗ್ರಾಹಕರು ಆರ್ಡರ್ ಮಾಡಿದ ತಕ್ಷಣ ಇಲ್ಲಿ ಕಾಣಿಸಿಕೊಳ್ಳುತ್ತದೆ!',
    status_new_order: 'ಹೊಸ ಆರ್ಡರ್',
    status_preparing: 'ತಯಾರಾಗುತ್ತಿದೆ',
    status_ready: 'ಪಿಕಪ್‌ಗೆ ಸಿದ್ಧವಾಗಿದೆ',
    status_completed: 'ಪೂರ್ಣಗೊಂಡಿದೆ',
    status_rejected: 'ತಿರಸ್ಕರಿಸಲಾಗಿದೆ',
    accept_order_btn: 'ಆರ್ಡರ್ ಸ್ವೀಕರಿಸಿ',
    reject_order_btn: 'ತಿರಸ್ಕರಿಸಿ',
    mark_ready_btn: 'ಆಹಾರ ಸಿದ್ಧವಾಗಿದೆ ಎಂದು ಗುರುತಿಸಿ',
    complete_order_btn: 'ಆರ್ಡರ್ ಪೂರ್ಣಗೊಳಿಸಿ',
    dishes_label: 'ಖಾದ್ಯಗಳು:',
    just_now: 'ಈಗಷ್ಟೇ',
    enter_rejection_reason: 'ತಿರಸ್ಕರಿಸಲು ಕಾರಣವನ್ನು ನಮೂದಿಸಿ:',

    chef_portal: 'ಮನೆ ಅಡುಗೆಯವರ ಹೆಮ್ಮೆಯ ವೇದಿಕೆ',
    authentic_tagline: 'ಮನೆಯ ರುಚಿ ಮತ್ತು ಪ್ರೀತಿಯಿಂದ ತಯಾರಿಸಿದ ಶುದ್ಧ ಆಹಾರ',
    sign_in: 'ಚೆಫ್ ಲಾಗಿನ್',
    sign_up: 'ಹೊಸ ಚೆಫ್ ನೋಂದಣಿ',
    chef_email_address: 'ಚೆಫ್ ಇಮೇಲ್ ವಿಳಾಸ',
    email_address: 'ಇಮೇಲ್ ವಿಳಾಸ',
    password: 'ಪಾಸ್‌ವರ್ಡ್',
    mobile_number: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    set_password: 'ಹೊಸ ಪಾಸ್‌ವರ್ಡ್',
    send_otp: '4 ಅಂಕಿಗಳ OTP ಕಳುಹಿಸಿ',
    enter_otp: '4 ಅಂಕಿಗಳ OTP ನಮೂದಿಸಿ',
    verify_proceed: 'ದೃಢೀಕರಿಸಿ ಮುಂದುವರಿಯಿರಿ',
    resend_code: 'ಮತ್ತೆ ಕೋಡ್ ಕಳುಹಿಸಿ',
    already_chef: 'ಈಗಾಗಲೇ ನೋಂದಾಯಿಸಿಕೊಂಡಿದ್ದೀರಾ?',
    new_chef_prompt: 'ಹೊಸ ಚೆಫ್ ಆಗಿದ್ದೀರಾ?',
    register_kitchen: 'ನಿಮ್ಮ ಅಡುಗೆಮನೆ ನೋಂದಾಯಿಸಿ',
    signing_in: 'ಲಾಗಿನ್ ಆಗುತ್ತಿದೆ...',
    sending_otp: 'OTP ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ...',
    verify_otp_title: 'OTP ದೃಢೀಕರಿಸಿ',
    verify_otp_subtitle: 'ನಿಮ್ಮ ಮೊಬೈಲ್ ಮತ್ತು ಇಮೇಲ್‌ಗೆ ಕಳುಹಿಸಲಾದ 4 ಅಂಕಿಗಳ ಕೋಡ್ ನಮೂದಿಸಿ',
    verify_and_continue: 'ದೃಢೀಕರಿಸಿ ಅಡುಗೆಮನೆ ವಿವರಗಳಿಗೆ ಮುಂದುವರಿಯಿರಿ',
    change_email_mobile: '← ಇಮೇಲ್ ಅಥವಾ ಮೊಬೈಲ್ ಬದಲಾಯಿಸಿ',

    step_2_title: 'ಹಂತ 2 / 3 • ಅಡುಗೆಮನೆ ಮತ್ತು ನೈರ್ಮಲ್ಯ',
    amma_chef_photo: 'ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ (Upload Photo)',
    kitchen_name: 'ಅಡುಗೆಮನೆ ಹೆಸರು',
    kitchen_name_placeholder: 'ಉದಾ., ಅಮ್ಮನ ಅಡುಗೆ ಮನೆ',
    owner_full_name: 'ಮಾಲೀಕರ ಪೂರ್ಣ ಹೆಸರು',
    owner_name_placeholder: 'ನಿಮ್ಮ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
    fssai_title: 'FSSAI ನೋಂದಣಿ / ಆಹಾರ ಸುರಕ್ಷತಾ ಸಂಖ್ಯೆ',
    fssai_placeholder: '14 ಅಂಕಿಗಳ FSSAI ಸಂಖ್ಯೆ',
    fssai_verified: 'ಸರ್ಕಾರಿ API ದೃಢೀಕೃತವಾಗಿದೆ',
    fssai_verifying: 'FoSCoS ಪೋರ್ಟಲ್‌ಗೆ ಸಂಪರ್ಕಿಸಲಾಗುತ್ತಿದೆ...',
    kitchen_address: 'ಅಡುಗೆಮನೆ ವಿಳಾಸ ಮತ್ತು ಸ್ಥಳ',
    kitchen_address_placeholder: 'ಮನೆ ನಂ., ರಸ್ತೆ, ಪ್ರದೇಶ, ನಗರ',
    privacy_shield: 'ಚೆಫ್ ಗೌಪ್ಯತೆ: ಆರ್ಡರ್ ಪಿಕಪ್ ಸಮಯದಲ್ಲಿ ಮಾತ್ರ ಗ್ರಾಹಕರಿಗೆ ವಿಳಾಸ ತೋರಿಸಲಾಗುತ್ತದೆ.',
    cuisine_specialties: 'ಅಡುಗೆಯ ವಿಶೇಷತೆಗಳು (ಅನ್ವಯವಾಗುವುದನ್ನು ಆರಿಸಿ)',
    pure_veg: 'ಶುದ್ಧ ಸಸ್ಯಾಹಾರಿ',
    south_indian: 'ದಕ್ಷಿಣ ಭಾರತೀಯ',
    north_indian: 'ಉತ್ತರ ಭಾರತೀಯ',
    home_sweets: 'ಮನೆಯ ಸಿಹಿ ಮತ್ತು ತಿನಿಸುಗಳು',
    andhra_style: 'ಖಾರದ ಆಂಧ್ರ ಶೈಲಿ',
    safety_declaration_title: 'ಆಹಾರ ನೈರ್ಮಲ್ಯ ಮತ್ತು ನ್ಯಾಯಯುತ ಬೆಲೆ ಪ್ರತಿಜ್ಞೆ:',
    safety_declaration_desc: 'ನನ್ನ ಮನೆಯ ಅಡುಗೆಮನೆಯಿಂದ ಶುದ್ಧ, ಆರೋಗ್ಯಕರ ಮತ್ತು ಗುಣಮಟ್ಟದ ಆಹಾರವನ್ನು ಒದಗಿಸುತ್ತೇನೆ ಎಂದು ಪ್ರತಿಜ್ಞೆ ಮಾಡುತ್ತೇನೆ.',
    continue_to_banking: 'ಬ್ಯಾಂಕ್ ವಿವರಗಳಿಗೆ ಮುಂದುವರಿಯಿರಿ',

    banking_title: 'ಬ್ಯಾಂಕ್ ಖಾತೆ ಮತ್ತು ಪಾವತಿಗಳು',
    step_3_title: 'ಹಂತ 3 / 3 • ಸಾಪ್ತಾಹಿಕ ನೇರ ಪಾವತಿಗಳು',
    account_holder: 'ಖಾತೆದಾರರ ಹೆಸರು',
    account_holder_placeholder: 'ಬ್ಯಾಂಕ್ ಪಾಸ್‌ಬುಕ್‌ನಲ್ಲಿರುವಂತೆ ಹೆಸರು',
    bank_name: 'ಬ್ಯಾಂಕ್ ಹೆಸರು',
    bank_name_placeholder: 'ಉದಾ., ಕೆನರಾ ಬ್ಯಾಂಕ್, SBI, HDFC',
    account_number: 'ಬ್ಯಾಂಕ್ ಖಾತೆ ಸಂಖ್ಯೆ',
    ifsc_code: 'IFSC ಕೋಡ್',
    upi_id: 'UPI ಐಡಿ (ತ್ವರಿತ ಪಾವತಿಗಾಗಿ)',
    upi_placeholder: 'ಉದಾ., hesaru@okaxis',
    direct_payout_title: '100% ನೇರ ಬ್ಯಾಂಕ್ ಪಾವತಿ ಭರವಸೆ',
    direct_payout_desc: 'ನಿಮ್ಮ ಸಾಪ್ತಾಹಿಕ ಗಳಿಕೆಯು ಯಾವುದೇ ಕಮಿಷನ್ ಕಡಿತವಿಲ್ಲದೆ ನೇರವಾಗಿ ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಖಾತೆಗೆ ಜಮೆಯಾಗುತ್ತದೆ.',
    open_kitchen_btn: 'ಅಡುಗೆಮನೆ ತೆರೆಯಿರಿ ಮತ್ತು ಆರ್ಡರ್ ಸ್ವೀಕರಿಸಿ',
    back_to_kitchen_btn: 'ಅಡುಗೆಮನೆ ವಿವರಗಳಿಗೆ ಹಿಂತಿರುಗಿ',

    available_balance: 'ಲಭ್ಯವಿರುವ ಬಾಕಿ ಮೊತ್ತ',
    secure_payouts: 'ಸುರಕ್ಷಿತ ಪಾವತಿಗಳು',
    pending_settlement: 'ಬಾಕಿ ಉಳಿದ ಮೊತ್ತ',
    available_in_24h: '24 ಗಂಟೆಗಳಲ್ಲಿ ಲಭ್ಯವಾಗಲಿದೆ',
    withdraw_instantly: 'ತಕ್ಷಣವೇ ಬ್ಯಾಂಕ್‌ಗೆ ವರ್ಗಾಯಿಸಿ',
    transferring: 'ವರ್ಗಾಯಿಸಲಾಗುತ್ತಿದೆ...',
    total_earnings: 'ಒಟ್ಟು ಗಳಿಕೆ',
    lifetime_revenue: 'ಇಲ್ಲಿಯವರೆಗಿನ ಒಟ್ಟು ಗಳಿಕೆ',
    active_mode: 'ಸಕ್ರಿಯ ಮೋಡ್',
    linked: 'ಲಿಂಕ್ ಮಾಡಲಾಗಿದೆ',
    not_linked: 'ಲಿಂಕ್ ಮಾಡಲಾಗಿಲ್ಲ',
    upi_active: 'UPI ಸಕ್ರಿಯವಾಗಿದೆ',
    bank_active: 'ಬ್ಯಾಂಕ್ ಸಕ್ರಿಯವಾಗಿದೆ',
    setup_required: 'ಸೆಟಪ್ ಅಗತ್ಯವಿದೆ',
    payout_destination: 'ಪಾವತಿ ತಲುಪುವ ಸ್ಥಳ',
    upi_id_tab: 'UPI ಐಡಿ',
    bank_account_tab: 'ಬ್ಯಾಂಕ್ ಖಾತೆ',
    primary_upi_id: 'ಪ್ರಾಥಮಿಕ UPI ಐಡಿ',
    edit_upi: 'UPI ಬದಲಾಯಿಸಿ',
    enter_upi_id: 'UPI ಐಡಿ ನಮೂದಿಸಿ',
    save_upi: 'UPI ಉಳಿಸಿ',
    change_ac: 'ಖಾತೆ ಬದಲಾಯಿಸಿ',
    penny_drop_note: 'ಬ್ಯಾಂಕ್ ಖಾತೆ ವಿವರಗಳನ್ನು ಬ್ಯಾಂಕಿಂಗ್ ಗೇಟ್‌ವೇ ಮೂಲಕ ತಕ್ಷಣ ಪರಿಶೀಲಿಸಲಾಗುತ್ತದೆ.',
    name_as_per_bank: 'ಬ್ಯಾಂಕ್ ದಾಖಲೆಗಳ ಪ್ರಕಾರ ಹೆಸರು',
    enter_ac_digits: '9 ರಿಂದ 18 ಅಂಕಿಗಳ ಖಾತೆ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
    verifying_bank: 'ಬ್ಯಾಂಕ್‌ನೊಂದಿಗೆ ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...',
    verify_save_ac: 'ಪರಿಶೀಲಿಸಿ ಖಾತೆಯನ್ನು ಉಳಿಸಿ',
    recent_payouts_orders: 'ಇತ್ತೀಚಿನ ಪಾವತಿಗಳು ಮತ್ತು ಆರ್ಡರ್‌ಗಳು',
    last_30_days: 'ಕಳೆದ 30 ದಿನಗಳು',
    no_transactions_yet: 'ಇನ್ನೂ ಯಾವುದೇ ವಹಿವಾಟು ನಡೆದಿಲ್ಲ',
    transactions_desc: 'ನಿಮ್ಮ ಆರ್ಡರ್‌ಗಳು ಮತ್ತು ಹಿಂಪಡೆಯುವಿಕೆಗಳ ವಿವರಗಳು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತವೆ.',

    open: 'ತೆರೆದಿದೆ',
    closed: 'ಮುಚ್ಚಿದೆ',
    share_kitchen_prompt: 'ಗ್ರಾಹಕರು ನಿಮ್ಮ ಅಡುಗೆಮನೆಯನ್ನು ನೋಡಬೇಕೆ?',
    share_profile_btn: 'ಪ್ರೊಫೈಲ್ ಲಿಂಕ್ ಹಂಚಿಕೊಳ್ಳಿ',
    link_copied: 'ಲಿಂಕ್ ನಕಲಿಸಲಾಗಿದೆ! ✓',
    kitchen_profile_details: 'ಅಡುಗೆಮನೆ ಪ್ರೊಫೈಲ್ ವಿವರಗಳು',
    edit_profile: 'ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
    cancel: 'ರದ್ದು',
    save_changes: 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    location_landmark: 'ಸ್ಥಳ / ಲ್ಯಾಂಡ್‌ಮಾರ್ಕ್',
    phone_number_label: 'ಫೋನ್ ಸಂಖ್ಯೆ',
    email_address_label: 'ಇಮೇಲ್ ವಿಳಾಸ',
    chef_bio: 'ಚೆಫ್ ಬಯೋಗ್ರಫಿ',
    instagram_handle: 'ಇನ್‌ಸ್ಟಾಗ್ರಾಮ್ / ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮ',
    change_profile_picture: 'ಪ್ರೊಫೈಲ್ ಫೋಟೋ ಬದಲಾಯಿಸಿ',
    chef_name: 'ಚೆಫ್ ಹೆಸರು',
    customer_reviews_title: 'ಗ್ರಾಹಕರ ವಿಮರ್ಶೆಗಳು ಮತ್ತು ರೇಟಿಂಗ್‌ಗಳು',
    overall_rating: 'ಒಟ್ಟಾರೆ ರೇಟಿಂಗ್:',
    reviews_count: 'ವಿಮರ್ಶೆಗಳು',
    chef_dashboard_badge: 'ಚೆಫ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    no_reviews_yet: 'ಗ್ರಾಹಕರಿಂದ ಯಾವುದೇ ವಿಮರ್ಶೆಗಳು ಬಂದಿಲ್ಲ.',
    profile_updated_success: 'ಪ್ರೊಫೈಲ್ ಮತ್ತು ಸ್ಥಳ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ!',

    no_notifications_yet: 'ಯಾವುದೇ ಹೊಸ ಅಧಿಸೂಚನೆಗಳಿಲ್ಲ.',
    close: 'ಮುಚ್ಚಿ',
    got_it: 'ಅರ್ಥವಾಯಿತು',
    push_notifications: 'ಪುಶ್ ಅಧಿಸೂಚನೆಗಳು',
    receive_alerts: 'ಹೊಸ ಆರ್ಡರ್‌ಗಳಿಗಾಗಿ ಎಚ್ಚರಿಕೆಗಳನ್ನು ಸ್ವೀಕರಿಸಿ',
    auto_accept_orders: 'ಸ್ವಯಂ-ಸ್ವೀಕಾರ ಆರ್ಡರ್‌ಗಳು',
    auto_accept_desc: 'ಸಿದ್ಧ ಸ್ಲಾಟ್‌ಗಳನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಸ್ವೀಕರಿಸಿ',
    log_out: 'ಲಾಗ್ ಔಟ್',
    delete_account: 'ಖಾತೆ ಅಳಿಸಿ',
    save_close: 'ಉಳಿಸಿ ಮತ್ತು ಮುಚ್ಚಿ',
    delete_account_warning: 'ಈ ಕ್ರಿಯೆಯು ನಿಮ್ಮ ಎಲ್ಲಾ ಪ್ರೊಫೈಲ್ ಡೇಟಾ, ಮೆನು ಮತ್ತು ಗಳಿಕೆಯನ್ನು ಶಾಶ್ವತವಾಗಿ ಅಳಿಸುತ್ತದೆ.',
    send_verification_otp: 'ದೃಢೀಕರಣ OTP ಕಳುಹಿಸಿ',
    verify_permanently_delete: 'ದೃಢೀಕರಿಸಿ ಮತ್ತು ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಿ',

    daily_hygiene_required: 'ದೈನಂದಿನ ಅಡುಗೆಮನೆ ಫೋಟೋ ಅಗತ್ಯವಿದೆ',
    daily_hygiene_desc: 'ಆರ್ಡರ್ ಸ್ವೀಕರಿಸುವ ಮೊದಲು ನಿಮ್ಮ ಸ್ವಚ್ಛ ಅಡುಗೆ ಕೌಂಟರ್ ಫೋಟೋ ತೆಗೆಯಿರಿ.',
    daily_hygiene_verified: 'ಇಂದಿನ ನೈರ್ಮಲ್ಯವನ್ನು ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    daily_hygiene_verified_desc: 'ಲೈವ್ ಕ್ಯಾಮೆರಾ ಮೂಲಕ ಸೆರೆಹಿಡಿಯಲಾಗಿದೆ. ಗ್ರಾಹಕರು ಇದನ್ನು ನೋಡಬಹುದು!',
    open_camera_btn: 'ಕ್ಯಾಮೆರಾ ತೆರೆದು ಫೋಟೋ ತೆಗೆಯಿರಿ',
    retake_camera_btn: 'ಮತ್ತೆ ಫೋಟೋ ತೆಗೆಯಿರಿ',
    direct_camera_btn: 'ಲೈವ್ ಕ್ಯಾಮೆರಾ',
    live_view: 'ಲೈವ್ ನೋಟ',
    point_camera_tip: 'ಕ್ಯಾಮೆರಾವನ್ನು ಸ್ವಚ್ಛ ಅಡುಗೆ ಕೌಂಟರ್‌ಗೆ ತಿರುಗಿಸಿ ಕ್ಯಾಪ್ಚರ್ ಒತ್ತಿರಿ.',

    menu_portions_title: 'ಅಡುಗೆಮನೆ ಮೆನು ಮತ್ತು ಪ್ರಮಾಣ',
    menu_portions_subtitle: 'ಖಾದ್ಯಗಳನ್ನು ಸೇರಿಸಿ ಮತ್ತು ಲಭ್ಯವಿರುವ ಪ್ರಮಾಣವನ್ನು ನಿರ್ವಹಿಸಿ',
    add_dish_btn: 'ಖಾದ್ಯ ಸೇರಿಸಿ',
    portions_label: 'ಪ್ರಮಾಣ:',
    edit_btn: 'ಸಂಪಾದಿಸಿ',
    mark_sold_out: 'ಖಾಲಿಯಾಗಿದೆ ಎಂದು ಗುರುತಿಸಿ',
    mark_available: 'ಲಭ್ಯವಿದೆ ಎಂದು ಗುರುತಿಸಿ',
    available_badge: 'ಲಭ್ಯವಿದೆ',
    sold_out_badge: 'ಖಾಲಿಯಾಗಿದೆ',
    add_signature_dish: 'ವಿಶೇಷ ಖಾದ್ಯ ಸೇರಿಸಿ',
    edit_dish_title: 'ಖಾದ್ಯದ ವಿವರಗಳನ್ನು ಸಂಪಾದಿಸಿ',
    dish_photo_optional: 'ಖಾದ್ಯದ ಫೋಟೋ (ಐಚ್ಛಿಕ)',
    upload_photo: 'ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    change_photo: 'ಫೋಟೋ ಬದಲಾಯಿಸಿ',
    remove_photo: 'ತೆಗೆದುಹಾಕಿ',
    dish_name_label: 'ಖಾದ್ಯದ ಹೆಸರು',
    dish_name_placeholder: 'ಉದಾ., ತುಪ್ಪದ ಮಸಾಲೆ ದೋಸೆ / ಸಾಂಬಾರ್ ಅನ್ನ',
    meal_slot_label: 'ಊಟದ ಸಮಯ',
    breakfast: 'ಬೆಳಗಿನ ಉಪಾಹಾರ',
    lunch: 'ಮಧ್ಯಾಹ್ನದ ಊಟ',
    dinner: 'ರಾತ್ರಿಯ ಊಟ',
    snacks: 'ಸಂಜೆಯ ತಿಂಡಿ ಮತ್ತು ಸಿಹಿತಿಂಡಿ',
    food_type_label: 'ಆಹಾರದ ವಿಧ',
    price_per_plate: 'ಪ್ರತಿ ಪ್ಲೇಟ್ ಬೆಲೆ (₹)',
    daily_portions_label: 'ದೈನಂದಿನ ಪ್ರಮಾಣ',
    description_label: 'ವಿವರಣೆ ಮತ್ತು ಪದಾರ್ಥಗಳು',
    description_placeholder: 'ಮನೆಯ ಸಾಂಪ್ರದಾಯಿಕ ತಯಾರಿಕೆಯ ಶೈಲಿಯನ್ನು ವಿವರಿಸಿ...',
    save_dish_btn: 'ಉಳಿಸಿ ಮತ್ತು ಮೆನುಗೆ ಸೇರಿಸಿ',
    update_dish_btn: 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    empty_menu_title: 'ನಿಮ್ಮ ಮೆನು ಪ್ರಸ್ತುತ ಖಾಲಿಯಾಗಿದೆ.',
    empty_menu_desc: 'ನಿಮ್ಮ ಮೊದಲ ರುಚಿಕರವಾದ ಮನೆಯ ಅಡುಗೆಯನ್ನು ಸೇರಿಸಲು ಮೇಲೆ "+ ಖಾದ್ಯ ಸೇರಿಸಿ" ಒತ್ತಿರಿ!'
  },

  // ==========================================
  // 6. MALAYALAM (മലയാളം)
  // ==========================================
  ml: {
    homepot_chef: 'ഹോംപോട്ട് ഷെഫ്',
    homepot_kitchen: 'ഹോംപോട്ട് അടുക്കള',
    partner_portal: 'അമ്മമാരുടെയും വീട്ടമ്മമാരുടെയും പാചക വേദി',
    manage_live_orders: 'തത്സമയ ഓർഡറുകളും ദൈനംദിന മെനുവും കൈകാര്യം ചെയ്യുക',
    cook_with_love: 'സ്നേഹത്തോടെ പാകം ചെയ്യാം • അഭിമാനത്തോടെ സമ്പാദിക്കാം',
    kitchen_open: 'അടുക്കള തുറന്നിരിക്കുന്നു',
    kitchen_closed: 'അടുക്കള അടച്ചിരിക്കുന്നു',
    tap_to_change: 'മാറ്റാൻ ടാപ്പ് ചെയ്യുക',
    live_orders: 'തത്സമയ ഓർഡറുകൾ',
    menu: 'ഭക്ഷണ മെനു',
    bankings: 'ബാങ്ക് അക്കൗണ്ട്',
    profile: 'പ്രൊഫൈൽ',
    notifications: 'അറിയിപ്പുകൾ',
    help_support: 'സഹായവും പിന്തുണയും',
    settings: 'ക്രമീകരണങ്ങൾ',
    choose_language: 'ഭാഷ മാറ്റുക',

    live_orders_subtitle: 'പുതിയ ഉപഭോക്തൃ ഓർഡറുകൾ തത്സമയം സ്വീകരിക്കുക',
    active: 'സജീവം',
    no_orders_queued: 'നിലവിൽ പുതിയ ഓർഡറുകൾ ഒന്നുമില്ല. ഉപഭോക്താക്കൾ ഓർഡർ ചെയ്യുമ്പോൾ ഇവിടെ ദൃശ്യമാകും!',
    status_new_order: 'പുതിയ ഓർഡർ',
    status_preparing: 'പാകം ചെയ്യുന്നു',
    status_ready: 'പിക്കപ്പിന് തയ്യാർ',
    status_completed: 'പൂർത്തിയായി',
    status_rejected: 'നിരസിച്ചു',
    accept_order_btn: 'ഓർഡർ സ്വീകരിക്കുക',
    reject_order_btn: 'നിരസിക്കുക',
    mark_ready_btn: 'ഭക്ഷണം തയ്യാർ എന്ന് രേഖപ്പെടുത്തുക',
    complete_order_btn: 'ഓർഡർ പൂർത്തിയാക്കുക',
    dishes_label: 'വിഭവങ്ങൾ:',
    just_now: 'ഇപ്പോൾ തന്നെ',
    enter_rejection_reason: 'നിരസിക്കാനുള്ള കാരണം നൽകുക:',

    chef_portal: 'അമ്മമാരുടെയും വീട്ടമ്മമാരുടെയും പാചക വേദി',
    authentic_tagline: 'നാടൻ രുചിയും സ്നേഹവും നിറഞ്ഞ ശുദ്ധമായ ഭക്ഷണം',
    sign_in: 'ഷെഫ് ലോഗിൻ',
    sign_up: 'പുതിയ ഷെഫ് രജിസ്ട്രേഷൻ',
    chef_email_address: 'ഷെഫ് ഇമെയിൽ വിലാസം',
    email_address: 'ഇമെയിൽ വിലാസം',
    password: 'പാസ്‌വേഡ്',
    mobile_number: 'മൊബൈൽ നമ്പർ',
    set_password: 'പുതിയ പാസ്‌വേഡ് നൽകുക',
    send_otp: '4 അക്ക OTP അയയ്ക്കുക',
    enter_otp: '4 അക്ക OTP നൽകുക',
    verify_proceed: 'പരിശോധിച്ച് തുടരുക',
    resend_code: 'വീണ്ടും കോഡ് അയയ്ക്കുക',
    already_chef: 'നേരത്തെ രജിസ്റ്റർ ചെയ്തിട്ടുണ്ടോ?',
    new_chef_prompt: 'പുതിയ ഷെഫ് ആണോ?',
    register_kitchen: 'നിങ്ങളുടെ അടുക്കള രജിസ്റ്റർ ചെയ്യുക',
    signing_in: 'ലോഗിൻ ചെയ്യുന്നു...',
    sending_otp: 'OTP അയയ്ക്കുന്നു...',
    verify_otp_title: 'OTP പരിശോധിക്കുക',
    verify_otp_subtitle: 'മൊബൈലിലും ഇമെയിലിലും ലഭിച്ച 4 അക്ക കോഡ് നൽകുക',
    verify_and_continue: 'പരിശോധിച്ച് അടുക്കള വിവരങ്ങളിലേക്ക് കടക്കുക',
    change_email_mobile: '← ഇമെയിൽ അല്ലെങ്കിൽ മൊബൈൽ നമ്പർ മാറ്റുക',

    step_2_title: 'ഘട്ടം 2 / 3 • അടുക്കളയും ശുചിത്വവും',
    amma_chef_photo: 'ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക (Upload Photo)',
    kitchen_name: 'അടുക്കളയുടെ പേര്',
    kitchen_name_placeholder: 'ഉദാ., അമ്മയുടെ അടുക്കള',
    owner_full_name: 'ഉടമസ്ഥന്റെ പൂർണ്ണമായ പേര്',
    owner_name_placeholder: 'നിങ്ങളുടെ പേര് നൽകുക',
    fssai_title: 'FSSAI രജിസ്ട്രേഷൻ / ഭക്ഷ്യസുരക്ഷാ നമ്പർ',
    fssai_placeholder: '14 അക്ക FSSAI നമ്പർ',
    fssai_verified: 'സർക്കാർ API പരിശോധിച്ചുറപ്പിച്ചു',
    fssai_verifying: 'FoSCoS പോർട്ടലിലേക്ക് ബന്ധിപ്പിക്കുന്നു...',
    kitchen_address: 'അടുക്കള വിലാസവും സ്ഥലവും',
    kitchen_address_placeholder: 'ഡോർ നമ്പർ, വഴി, പ്രദേശം, നഗരം',
    privacy_shield: 'ഷെഫ് സുരക്ഷ: ഭക്ഷണം പിക്കപ്പ് ചെയ്യുന്ന സമയത്ത് മാത്രമേ ഉപഭോക്താവിന് വിലാസം കാണിക്കൂ.',
    cuisine_specialties: 'പാചക രീതികൾ (ബാധകമായവ തിരഞ്ഞെടുക്കുക)',
    pure_veg: 'ശുദ്ധ സസ്യാഹാരം',
    south_indian: 'ദക്ഷിണേന്ത്യൻ വിഭവങ്ങൾ',
    north_indian: 'ഉത്തരേന്ത്യൻ വിഭവങ്ങൾ',
    home_sweets: 'വീട്ടിലുണ്ടാക്കിയ പലഹാരങ്ങളും മധുരപലഹാരങ്ങളും',
    andhra_style: 'ആന്ധ്ര സ്പൈസി വിഭവങ്ങൾ',
    safety_declaration_title: 'ഭക്ഷ്യ ശുചിത്വവും ന്യായവിലയും സംബന്ധിച്ച പ്രതിജ്ഞ:',
    safety_declaration_desc: 'വീട്ടിലെ അടുക്കളയിൽ ശുചിത്വത്തോടും നല്ല ചേരുവകളോടും കൂടി ഭക്ഷണം തയ്യാറാക്കുമെന്ന് ഞാൻ ഉറപ്പ് നൽകുന്നു.',
    continue_to_banking: 'ബാങ്ക് വിവരങ്ങളിലേക്ക് പോകുക',

    banking_title: 'ബാങ്ക് അക്കൗണ്ടും പേയ്‌മെന്റുകളും',
    step_3_title: 'ഘട്ടം 3 / 3 • പ്രതിവാര നേരിട്ടുള്ള ബാങ്ക് പേയ്‌മെന്റ്',
    account_holder: 'അക്കൗണ്ട് ഉടമയുടെ പേര്',
    account_holder_placeholder: 'ബാങ്ക് പാസ്ബുക്കിൽ ഉള്ളതുപോലെ പേര്',
    bank_name: 'ബാങ്കിന്റെ പേര്',
    bank_name_placeholder: 'ഉദാ., ഫെഡറൽ ബാങ്ക്, SBI, HDFC',
    account_number: 'ബാങ്ക് അക്കൗണ്ട് നമ്പർ',
    ifsc_code: 'IFSC കോഡ്',
    upi_id: 'UPI ഐഡി (തത്സമയ ഇടപാടുകൾക്കായി)',
    upi_placeholder: 'ഉദാ., peru@okaxis',
    direct_payout_title: '100% നേരിട്ടുള്ള ബാങ്ക് കൈമാറ്റ ഉറപ്പ്',
    direct_payout_desc: 'നിങ്ങളുടെ പ്രതിവാര അധ്വാനത്തിന്റെ വരുമാനം കമ്മീഷൻ കിഴിവുകളില്ലാതെ നേരിട്ട് നിങ്ങളുടെ ബാങ്ക് അക്കൗണ്ടിൽ എത്തും.',
    open_kitchen_btn: 'അടുക്കള തുറന്ന് ഓർഡറുകൾ സ്വീകരിച്ചു തുടങ്ങുക',
    back_to_kitchen_btn: 'അടുക്കള വിവരങ്ങളിലേക്ക് തിരികെ പോകുക',

    available_balance: 'ലഭ്യമായ ബാലൻസ്',
    secure_payouts: 'സുരക്ഷിത പേയ്‌മെന്റുകൾ',
    pending_settlement: 'തീർപ്പുകൽപ്പിക്കാത്ത തുക',
    available_in_24h: '24 മണിക്കൂറിനുള്ളിൽ ലഭ്യമാകും',
    withdraw_instantly: 'ഉടൻ ബാങ്കിലേക്ക് മാറ്റുക',
    transferring: 'പണം അയയ്ക്കുന്നു...',
    total_earnings: 'ആകെ വരുമാനം',
    lifetime_revenue: 'ഇതുവരെയുള്ള മൊത്തം വരുമാനം',
    active_mode: 'സജീവമായ മോഡ്',
    linked: 'ബന്ധിപ്പിച്ചു',
    not_linked: 'ബന്ധിപ്പിച്ചിട്ടില്ല',
    upi_active: 'UPI സജീവമാണ്',
    bank_active: 'ബാങ്ക് സജീവമാണ്',
    setup_required: 'സെറ്റപ്പ് ആവശ്യമാണ്',
    payout_destination: 'പണം ലഭിക്കുന്ന ഇടം',
    upi_id_tab: 'UPI ഐഡി',
    bank_account_tab: 'ബാങ്ക് അക്കൗണ്ട്',
    primary_upi_id: 'പ്രധാന UPI ഐഡി',
    edit_upi: 'UPI മാറ്റുക',
    enter_upi_id: 'UPI ഐഡി നൽകുക',
    save_upi: 'UPI സംരക്ഷിക്കുക',
    change_ac: 'അക്കൗണ്ട് മാറ്റുക',
    penny_drop_note: 'ബാങ്കിംഗ് ഗേറ്റ്‌വേകൾ വഴി ബാങ്ക് അക്കൗണ്ട് വിവരങ്ങൾ തത്സമയം പരിശോധിച്ചുറപ്പിക്കുന്നു.',
    name_as_per_bank: 'ബാങ്ക് രേഖകളിലെ പേര്',
    enter_ac_digits: '9 മുതൽ 18 അക്ക അക്കൗണ്ട് നമ്പർ നൽകുക',
    verifying_bank: 'ബാങ്കുമായി പരിശോധിക്കുന്നു...',
    verify_save_ac: 'പരിശോധിച്ച് അക്കൗണ്ട് സംരക്ഷിക്കുക',
    recent_payouts_orders: 'സമീപകാല പേയ്‌മെന്റുകളും ഓർഡറുകളും',
    last_30_days: 'കഴിഞ്ഞ 30 ദിവസം',
    no_transactions_yet: 'ഇതുവരെ ഇടപാടുകളൊന്നും നടന്നിട്ടില്ല',
    transactions_desc: 'നിങ്ങളുടെ ഓർഡറുകളും പണം പിൻവലിക്കലുകളും ഇവിടെ കാണാം.',

    open: 'തുറന്നിരിക്കുന്നു',
    closed: 'അടച്ചിരിക്കുന്നു',
    share_kitchen_prompt: 'ഉപഭോക്താക്കൾ നിങ്ങളുടെ അടുക്കള കാണണോ?',
    share_profile_btn: 'പ്രൊഫൈൽ ലിങ്ക് പങ്കിടുക',
    link_copied: 'ലിങ്ക് പകർത്തി! ✓',
    kitchen_profile_details: 'അടുക്കള പ്രൊഫൈൽ വിവരങ്ങൾ',
    edit_profile: 'വിവരങ്ങൾ മാറ്റുക',
    cancel: 'റദ്ദാക്കുക',
    save_changes: 'മാറ്റങ്ങൾ സംരക്ഷിക്കുക',
    location_landmark: 'സ്ഥലം / ലാൻഡ്‌മാർക്ക്',
    phone_number_label: 'ഫോൺ നമ്പർ',
    email_address_label: 'ഇമെയിൽ വിലാസം',
    chef_bio: 'ഷെഫ് ബയോ',
    instagram_handle: 'ഇൻസ്റ്റാഗ്രാം / സോഷ്യൽ ഹാൻഡിൽ',
    change_profile_picture: 'പ്രൊഫൈൽ ചിത്രം മാറ്റുക',
    chef_name: 'ഷെഫ് പേര്',
    customer_reviews_title: 'ഉപഭോക്തൃ അവലോകനങ്ങളും റേറ്റിംഗുകളും',
    overall_rating: 'മൊത്തത്തിലുള്ള റേറ്റിംഗ്:',
    reviews_count: 'അവലോകനങ്ങൾ',
    chef_dashboard_badge: 'ഷെഫ് ഡാഷ്‌ബോർഡ്',
    no_reviews_yet: 'ഇതുവരെ ഉപഭോക്തൃ അവലോകനങ്ങൾ വന്നിട്ടില്ല.',
    profile_updated_success: 'പ്രൊഫൈലും സ്ഥലവും വിജയകരമായി അപ്‌ഡേറ്റ് ചെയ്തു!',

    no_notifications_yet: 'പുതിയ ഓർഡർ അറിയിപ്പുകൾ ഒന്നുമില്ല.',
    close: 'അടയ്ക്കുക',
    got_it: 'മനസ്സിലായി',
    push_notifications: 'പുഷ് അറിയിപ്പുകൾ',
    receive_alerts: 'പുതിയ ഓർഡറുകൾക്കായി അലേർട്ടുകൾ നേടുക',
    auto_accept_orders: 'ഓട്ടോ-സ്വീകാരം',
    auto_accept_desc: 'തയ്യാറായ സ്ലോട്ടുകൾ സ്വയമേവ സ്വീകരിക്കുക',
    log_out: 'ലോഗ് ഔട്ട്',
    delete_account: 'അക്കൗണ്ട് ഇല്ലാതാക്കുക',
    save_close: 'സംരക്ഷിച്ച് അടയ്ക്കുക',
    delete_account_warning: 'ഈ പ്രവർത്തനം നിങ്ങളുടെ എല്ലാ ഡാറ്റയും ശാശ്വതമായി നീക്കം ചെയ്യും.',
    send_verification_otp: 'സ്ഥിരീകരണ OTP അയയ്ക്കുക',
    verify_permanently_delete: 'പരിശോധിച്ച് ശാശ്വതമായി ഇല്ലാതാക്കുക',

    daily_hygiene_required: 'ദൈനംദിന അടുക്കള ഫോട്ടോ ആവശ്യമാണ്',
    daily_hygiene_desc: 'ഓർഡറുകൾ തുടങ്ങുന്നതിന് മുൻപ് വൃത്തിയുള്ള പാചക കൗണ്ടറിന്റെ ലൈവ് ഫോട്ടോ എടുക്കുക.',
    daily_hygiene_verified: 'ഇന്നത്തെ അടുക്കള ശുചിത്വം സ്ഥിരീകരിച്ചു',
    daily_hygiene_verified_desc: 'ഇന്ന് ലൈവ് ക്യാമറയിലൂടെ എടുത്ത ചിത്രം. ഉപഭോക്താക്കൾക്ക് ഇത് കാണാൻ കഴിയും!',
    open_camera_btn: 'ക്യാമറ തുറന്ന് ചിത്രം പകർത്തുക',
    retake_camera_btn: 'വീണ്ടും ഫോട്ടോ എടുക്കുക',
    direct_camera_btn: 'തത്സമയ ക്യാമറ',
    live_view: 'തത്സമയ കാഴ്ച',
    point_camera_tip: 'ക്യാമറ വൃത്തിയുള്ള പാചക കൗണ്ടറിലേക്ക് തിരിച്ച് കാപ്ചർ അമർത്തുക.',

    menu_portions_title: 'അടുക്കള മെനുവും അളവുകളും',
    menu_portions_subtitle: 'വിഭവങ്ങൾ ചേർക്കുക, സമയം മാറ്റുക, ലഭ്യമായ അളവ് ക്രമീകരിക്കുക',
    add_dish_btn: 'വിഭവം ചേർക്കുക',
    portions_label: 'അളവ്:',
    edit_btn: 'മാറ്റുക',
    mark_sold_out: 'തീർന്നു എന്ന് അടയാളപ്പെടുത്തുക',
    mark_available: 'ലഭ്യമാണ് എന്ന് അടയാളപ്പെടുത്തുക',
    available_badge: 'ലഭ്യമാണ്',
    sold_out_badge: 'തീർന്നു',
    add_signature_dish: 'പ്രത്യേക നാടൻ വിഭവം ചേർക്കുക',
    edit_dish_title: 'വിഭവത്തിന്റെ വിവരങ്ങൾ തിരുത്തുക',
    dish_photo_optional: 'ഭക്ഷണ ഫോട്ടോ (വേണമെങ്കിൽ മാത്രം)',
    upload_photo: 'ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക',
    change_photo: 'ഫോട്ടോ മാറ്റുക',
    remove_photo: 'നീക്കം ചെയ്യുക',
    dish_name_label: 'വിഭവത്തിന്റെ പേര്',
    dish_name_placeholder: 'ഉദാ., നെയ് മസാല ദോശ / സാമ്പാർ സാദം',
    meal_slot_label: 'ഭക്ഷണ സമയം',
    breakfast: 'പ്രഭാതഭക്ഷണം',
    lunch: 'ഉച്ചഭക്ഷണം',
    dinner: 'അത്താഴം',
    snacks: 'വൈകുന്നേരത്തെ പലഹാരങ്ങൾ',
    food_type_label: 'ഭക്ഷണ തരം',
    price_per_plate: 'ഒരു പ്ലേറ്റ് നിരക്ക് (₹)',
    daily_portions_label: 'ദൈനംദിന അളവ്',
    description_label: 'വിവരണവും ചേരുവകളും',
    description_placeholder: 'നാടൻ രീതിയിലുള്ള പാചക ചേരുവകൾ വിവരിക്കുക...',
    save_dish_btn: 'സംരക്ഷിച്ച് മെനുവിൽ ചേർക്കുക',
    update_dish_btn: 'മാറ്റങ്ങൾ സംരക്ഷിക്കുക',
    empty_menu_title: 'നിങ്ങളുടെ മെനു നിലവിൽ ശൂന്യമാണ്.',
    empty_menu_desc: 'നിങ്ങളുടെ ആദ്യത്തെ രുചികരമായ നാടൻ വിഭവം ചേർക്കാൻ മുകളിലെ "+ വിഭവം ചേർക്കുക" അമർത്തുക!'
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [currentLang, setCurrentLang] = useState(() => {
    return localStorage.getItem('homepot_chef_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('homepot_chef_lang', currentLang);
    document.documentElement.lang = currentLang;
  }, [currentLang]);

  const t = (key) => {
    if (TRANSLATIONS[currentLang] && TRANSLATIONS[currentLang][key]) {
      return TRANSLATIONS[currentLang][key];
    }
    if (TRANSLATIONS['en'] && TRANSLATIONS['en'][key]) {
      return TRANSLATIONS['en'][key];
    }
    return key;
  };

  return (
    <LanguageContext.Provider value={{ currentLang, setCurrentLang, t, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
