import React, { createContext, useContext, useState, useEffect } from 'react';

export const LANGUAGES = [
  { code: 'en', label: 'English', name: 'English', flag: '🇬🇧' },
  { code: 'ta', label: 'தமிழ்', name: 'Tamil', flag: '🇮🇳' },
  { code: 'hi', label: 'हिंदी', name: 'Hindi', flag: '🇮🇳' },
  { code: 'te', label: 'తెలుగు', name: 'Telugu', flag: '🇮🇳' },
  { code: 'kn', label: 'ಕನ್ನಡ', name: 'Kannada', flag: '🇮🇳' },
  { code: 'ml', label: 'മലയാളം', name: 'Malayalam', flag: '🇮🇳' }
];

export const TRANSLATIONS = {
  // ==========================================
  // ENGLISH (en)
  // ==========================================
  en: {
    app_title: 'HomePot Delivery',
    home: 'Home',
    payout: 'Total Earned',
    profile: 'Profile',
    terms_privacy_notice: 'Terms and Privacy under the terms and Privacy list below.',

    // Welcome Page
    start_your_journey: 'Start Your Journey',
    deliver_fresh_earn: 'Deliver Fresh Home Food & Earn',
    daily_earnings_badge: '₹500+ Daily Earnings',
    live_tracking_badge: '5 km Radius Radar',
    login_btn: 'LOGIN',
    join_us_btn: 'JOIN US / SIGN UP',

    // Rider Auth (No Step 2A / 2B)
    enter_details_title: 'Enter Your Details',
    verify_phone_title: 'Verify Phone & Email',
    full_name_label: 'Full Name',
    full_name_placeholder: 'Kumar V.',
    email_id_label: 'Email ID',
    email_id_placeholder: 'kumar.delivery@gmail.com',
    phone_number_label: 'Phone Number',
    phone_placeholder: '+91 9876543210',
    accept_terms: 'I accept terms',
    send_otp_btn: 'SEND OTP',
    enter_6_digit_otp: 'Enter 6-digit OTP sent to',
    resend_otp: 'Resend OTP',
    verify_proceed_btn: 'VERIFY & PROCEED',
    sending_code: 'Sending verification code...',

    // KYC & Setup (No Step 2C)
    rider_kyc_title: 'Vehicle & Bank Details',
    vehicle_info_title: 'Registered Vehicle Details',
    vehicle_type: 'Vehicle Type',
    electric_scooter: 'Electric Scooter',
    petrol_bike: 'Petrol Bike / Motorcycle',
    bicycle: 'Bicycle / EV Cycle',
    vehicle_number: 'Vehicle Registration Number',
    driving_license_no: 'Driving License Number',
    operating_city: 'Operating City / Hub',
    bank_payout_title: 'Bank & UPI Settlement Details',
    account_holder_name: 'Account Holder Name',
    bank_account_number: 'Bank Account Number',
    ifsc_code: 'IFSC Code',
    upi_id_label: 'Primary UPI ID (GPay / PhonePe / Paytm)',
    complete_onboarding_btn: 'Complete Setup & Go Online',

    // Order Radar & Tracking (No countdown timer, pure plastic container)
    in_progress_tab: 'In Progress',
    history_tab: 'History',
    order_status_active: 'Active Delivery',
    est_delivery_time: 'Est: 20-25 mins',
    confirmed: 'Confirmed',
    cooking: 'Cooking',
    out_for_delivery: 'Out for Delivery',
    delivered: 'DELIVERED',
    cancelled: 'CANCELLED',
    kitchen_details: 'Kitchen details',
    pickup_address: 'Pickup address',
    drop_off_address: 'Drop-off address',
    view_order_items: 'View order items',
    meal_type: 'Meal Type',
    total_amount_collected: 'Total amount to be collected:',
    cod_badge: 'COD',
    paid_online_badge: 'PAID ONLINE',
    picked_up_btn: '>> Picked Up',
    delivered_btn: '-> Delivered',
    enter_delivery_otp: 'Enter Customer Delivery OTP',
    verify_otp_modal_title: 'Verify Customer Delivery OTP',
    customer_otp_hint: 'Ask the customer for the 4-digit code shown on their HomePot app before handing over food.',
    confirm_and_complete: 'Verify OTP & Complete Delivery',
    invalid_otp: 'Invalid OTP code. Please verify with customer.',
    
    // Sealed Container Packaging
    sealed_container_title: 'Hygienic Sealed Food Packaging',
    sealed_container_desc: 'Food delivered in tamper-proof disposable containers. No empty dabba return required.',

    available_orders_radar: 'Nearby Kitchen Orders (Within 5 km)',
    no_active_orders: 'No orders in progress right now. Nearby kitchen requests will appear below!',
    accept_order_btn: 'Accept Delivery',
    radar_searching: 'Scanning 5 km radius around you...',
    new_order_alert: 'New Home Order Alert!',
    km_away: 'km away',

    // Profile & SOS
    rider_verified: '4.8 / Verified',
    account_details: 'Account Details:',
    account_details_sub: 'Phone, Email, Registered Vehicle',
    documents: 'Documents:',
    driving_license: 'Driving License',
    rc_book: 'RC',
    preferences: 'Preferences:',
    preferences_sub: 'Language, Sound & Voice Alerts',
    bank_details: 'Bank Details:',
    bank_details_sub: 'Payment methods, Bank Account, UPI ID',
    support: 'Support:',
    contact_us: 'Contact Us,',
    sos_button: 'SOS Button',
    terms_of_service: 'Terms of Service',
    logout: 'Logout',
    sos_emergency_modal: 'Emergency SOS Alert',
    sos_warning: 'Pressing SOS will immediately broadcast your live GPS coordinates to emergency support and local authorities.',
    trigger_sos: 'CONFIRM & SEND SOS SIGNAL',
    cancel: 'Cancel',
    save_changes: 'Save Changes',

    // Confidential Total Earned
    total_earned: 'Total Earned',
    per_day_earned: 'Today',
    per_week_earned: 'This Week',
    per_month_earned: 'This Month',
    per_order_earned: 'Earned for this order',
    confidential_title: 'Confidential Earnings Locked',
    confidential_sub: 'Authenticate with Fingerprint, Face ID or Security PIN to view earnings',
    unlock_earnings_btn: 'Unlock Earnings',
    biometric_btn: 'Touch ID / Fingerprint / Face ID',
    or_enter_pin: 'Or Enter 4-Digit Security PIN / Password',
    pin_placeholder: 'Enter 4-digit PIN (default 1234)',
    unlock_now: 'Verify & Unlock',
    lock_again: 'Hide & Lock',
    withdraw_instantly: 'Withdraw to UPI Instantly',
    deliveries_completed: 'Completed Orders',
    recent_earnings: 'Recent Earnings by Order',
    transfer_success: 'Successfully transferred to UPI!'
  },

  // ==========================================
  // TAMIL (தமிழ்)
  // ==========================================
  ta: {
    app_title: 'ஹோம்பாட் டெலிவரி',
    home: 'முகப்பு',
    payout: 'மொத்த வருமானம்',
    profile: 'சுயவிவரம்',
    terms_privacy_notice: 'விதிமுறைகள் மற்றும் தனியுரிமைக் கொள்கைக்கு உட்பட்டது.',

    start_your_journey: 'உங்கள் பயணத்தை தொடங்குங்கள்',
    deliver_fresh_earn: 'சூடான வீட்டு உணவை வழங்கி சம்பாதிக்கவும்',
    daily_earnings_badge: 'தினமும் ₹500+ வருமானம்',
    live_tracking_badge: '5 கி.மீ எல்லை ரேடார்',
    login_btn: 'உள்நுழைக (LOGIN)',
    join_us_btn: 'புதிய ரைடர் பதிவு (SIGN UP)',

    enter_details_title: 'உங்கள் விவரங்களை உள்ளிடவும்',
    verify_phone_title: 'தொலைபேசியை சரிபார்க்கவும்',
    full_name_label: 'முழு பெயர்',
    full_name_placeholder: 'குமார் வி.',
    email_id_label: 'மின்னஞ்சல் முகவரி',
    email_id_placeholder: 'kumar.delivery@gmail.com',
    phone_number_label: 'தொலைபேசி எண்',
    phone_placeholder: '+91 9876543210',
    accept_terms: 'விதிமுறைகளை ஏற்கிறேன்',
    send_otp_btn: 'OTP அனுப்புக',
    enter_6_digit_otp: 'அனுப்பப்பட்ட 6-இலக்க OTP ஐ உள்ளிடவும்',
    resend_otp: 'மீண்டும் OTP அனுப்புக',
    verify_proceed_btn: 'சரிபார்த்து தொடரவும்',
    sending_code: 'சரிபார்ப்புக் குறியீடு அனுப்பப்படுகிறது...',

    rider_kyc_title: 'வாகனம் மற்றும் வங்கி விவரங்கள்',
    vehicle_info_title: 'பதிவு செய்யப்பட்ட வாகன விவரங்கள்',
    vehicle_type: 'வாகன வகை',
    electric_scooter: 'மின்சார ஸ்கூட்டர் (EV)',
    petrol_bike: 'பெட்ரோல் பைக் / மோட்டார் சைக்கிள்',
    bicycle: 'சைக்கிள்',
    vehicle_number: 'வாகன பதிவு எண்',
    driving_license_no: 'ஓட்டுநர் உரிம எண்',
    operating_city: 'பணியாற்றும் நகரம்',
    bank_payout_title: 'வங்கி & UPI கணக்கு விவரங்கள்',
    account_holder_name: 'கணக்கு வைத்திருப்பவர் பெயர்',
    bank_account_number: 'வங்கி கணக்கு எண்',
    ifsc_code: 'IFSC குறியீடு',
    upi_id_label: 'முக்கிய UPI ID (GPay / PhonePe)',
    complete_onboarding_btn: 'பதிவை முடித்து ஆன்லைன் செல்லவும்',

    in_progress_tab: 'செயலில் உள்ளது',
    history_tab: 'வரலாறு',
    order_status_active: 'செயலில் உள்ள டெலிவரி',
    est_delivery_time: 'மதிப்பிடப்பட்ட நேரம்: 20-25 நிமி',
    confirmed: 'உறுதி செய்யப்பட்டது',
    cooking: 'சமைக்கப்படுகிறது',
    out_for_delivery: 'டெலிவரிக்கு புறப்பட்டது',
    delivered: 'வழங்கப்பட்டது',
    cancelled: 'ரத்து செய்யப்பட்டது',
    kitchen_details: 'சமையலறை விவரங்கள்',
    pickup_address: 'பிக்அப் முகவரி',
    drop_off_address: 'டெலிவரி முகவரி',
    view_order_items: 'உணவு விவரங்கள்',
    meal_type: 'உணவு வகை',
    total_amount_collected: 'வாடிக்கையாளரிடம் பெறவேண்டிய தொகை:',
    cod_badge: 'ரொக்கம் (COD)',
    paid_online_badge: 'ஆன்லைன் கட்டணம்',
    picked_up_btn: '>> பார்சல் எடுக்கப்பட்டது',
    delivered_btn: '-> வழங்கப்பட்டது',
    enter_delivery_otp: 'வாடிக்கையாளர் OTP உள்ளிடவும்',
    verify_otp_modal_title: 'டெலிவரி OTP சரிபார்ப்பு',
    customer_otp_hint: 'உணவை வழங்குவதற்கு முன் வாடிக்கையாளரிடம் 4 இலக்க OTP குறியீட்டை கேட்கவும்.',
    confirm_and_complete: 'OTP சரிபார்த்து முடிக்கவும்',
    invalid_otp: 'தவறான OTP குறியீடு.',

    sealed_container_title: 'சீல் செய்யப்பட்ட சுகாதார உணவுப் பொட்டலம்',
    sealed_container_desc: 'பாதுகாப்பான பிளாஸ்டிக் பெட்டியில் வழங்கப்படுகிறது. காலி டப்பா எதுவும் திரும்பப் பெறத் தேவையில்லை.',

    available_orders_radar: 'அருகிலுள்ள சமையலறை ஆர்டர்கள் (5 கி.மீ)',
    no_active_orders: 'தற்போது ஆர்டர்கள் எதுவும் இல்லை. புதிய ஆர்டர்கள் கீழே தோன்றும்!',
    accept_order_btn: 'டெலிவரியை ஏற்கவும்',
    radar_searching: '5 கி.மீ சுற்றளவில் தேடுகிறது...',
    new_order_alert: 'புதிய ஆர்டர் வந்துள்ளது!',
    km_away: 'கி.மீ தொலைவில்',

    rider_verified: '4.8 / சரிபார்க்கப்பட்டது',
    account_details: 'கணக்கு விவரங்கள்:',
    account_details_sub: 'தொலைபேசி, மின்னஞ்சல், வாகனம்',
    documents: 'ஆவணங்கள்:',
    driving_license: 'ஓட்டுநர் உரிமம்',
    rc_book: 'ஆர்.சி புத்தகம்',
    preferences: 'விருப்பத்தேர்வுகள்:',
    preferences_sub: 'மொழி, எச்சரிக்கை ஒலிகள்',
    bank_details: 'வங்கி விவரங்கள்:',
    bank_details_sub: 'கட்டண முறைகள், UPI ID',
    support: 'உதவி மையம்:',
    contact_us: 'தொடர்பு கொள்ள,',
    sos_button: 'அவசர SOS பொத்தான்',
    terms_of_service: 'சேவை விதிமுறைகள்',
    logout: 'வெளியேறு',
    sos_emergency_modal: 'அவசர SOS எச்சரிக்கை',
    sos_warning: 'SOS பொத்தானை அழுத்தினால் உங்கள் நேரடி இருப்பிடம் உடனடியாக உதவி மையத்திற்கு பகிரப்படும்.',
    trigger_sos: 'உறுதி செய்து SOS அனுப்பு',
    cancel: 'ரத்து',
    save_changes: 'சேமிக்க',

    total_earned: 'மொத்த வருமானம்',
    per_day_earned: 'இன்று (நாள்)',
    per_week_earned: 'இந்த வாரம்',
    per_month_earned: 'இந்த மாதம்',
    per_order_earned: 'இந்த ஆர்டருக்கான வருமானம்',
    confidential_title: 'வருமான விவரம் பூட்டப்பட்டுள்ளது',
    confidential_sub: 'கைரேகை, முக அடையாளம் அல்லது பின் எண் மூலம் திறக்கவும்',
    unlock_earnings_btn: 'வருமானத்தை திறக்க',
    biometric_btn: 'கைரேகை / முக அங்கீகாரம்',
    or_enter_pin: 'அல்லது 4-இலக்க பாதுகாப்பு PIN / கடவுச்சொல்',
    pin_placeholder: '4 இலக்க PIN (இயல்புநிலை 1234)',
    unlock_now: 'சரிபார்த்து திறக்கவும்',
    lock_again: 'மறைக்க பூட்டவும்',
    withdraw_instantly: 'UPI மூலம் உடனடியாக பணத்தை எடுக்க',
    deliveries_completed: 'முடிக்கப்பட்ட ஆர்டர்கள்',
    recent_earnings: 'சமீபத்திய ஆர்டர் வருமானங்கள்',
    transfer_success: 'தொகை உங்கள் UPI கணக்கிற்கு அனுப்பப்பட்டது!'
  },

  // ==========================================
  // HINDI (हिंदी)
  // ==========================================
  hi: {
    app_title: 'होमपॉट डिलीवरी',
    home: 'होम',
    payout: 'कुल कमाई',
    profile: 'प्रोफाइल',
    terms_privacy_notice: 'नियम और गोपनीयता शर्तों के अधीन।',
    start_your_journey: 'अपनी यात्रा शुरू करें',
    deliver_fresh_earn: 'ताजा घर का खाना पहुंचाएं और कमाएं',
    daily_earnings_badge: 'रोजाना ₹500+ कमाई',
    live_tracking_badge: '5 किमी दायरा रडार',
    login_btn: 'लॉग इन करें',
    join_us_btn: 'साइन अप करें',
    enter_details_title: 'अपना विवरण दर्ज करें',
    verify_phone_title: 'फोन और ईमेल सत्यापित करें',
    full_name_label: 'पूरा नाम',
    full_name_placeholder: 'कुमार वी.',
    email_id_label: 'ईमेल आईडी',
    email_id_placeholder: 'kumar.delivery@gmail.com',
    phone_number_label: 'फ़ोन नंबर',
    phone_placeholder: '+91 9876543210',
    accept_terms: 'मुझे शर्तें स्वीकार हैं',
    send_otp_btn: 'ओटीपी भेजें',
    enter_6_digit_otp: '6 अंकों का ओटीपी दर्ज करें',
    resend_otp: 'पुनः ओटीपी भेजें',
    verify_proceed_btn: 'सत्यापित करें और आगे बढ़ें',
    sending_code: 'सत्यापन कोड भेजा जा रहा है...',
    rider_kyc_title: 'वाहन और बैंक विवरण',
    vehicle_info_title: 'पंजीकृत वाहन विवरण',
    vehicle_type: 'वाहन प्रकार',
    electric_scooter: 'इलेक्ट्रिक स्कूटर',
    petrol_bike: 'पेट्रोल बाइक',
    bicycle: 'साइकिल',
    vehicle_number: 'वाहन पंजीकरण संख्या',
    driving_license_no: 'ड्राइविंग लाइसेंस नंबर',
    operating_city: 'ऑपरेटिंग शहर',
    bank_payout_title: 'बैंक और यूपीआई विवरण',
    account_holder_name: 'खाता धारक का नाम',
    bank_account_number: 'बैंक खाता संख्या',
    ifsc_code: 'आईएफएससी कोड',
    upi_id_label: 'यूपीआई आईडी',
    complete_onboarding_btn: 'सेटअप पूरा करें',
    in_progress_tab: 'प्रगति पर',
    history_tab: 'इतिहास',
    order_status_active: 'सक्रिय डिलीवरी',
    est_delivery_time: 'समय: 20-25 मिनट',
    confirmed: 'पुष्ट',
    cooking: 'तैयार हो रहा है',
    out_for_delivery: 'डिलीवरी के लिए रवाना',
    delivered: 'डिलीवर किया गया',
    cancelled: 'रद्द',
    kitchen_details: 'रसोई विवरण',
    pickup_address: 'पिकअप पता',
    drop_off_address: 'डिलीवरी पता',
    view_order_items: 'ऑर्डर आइटम देखें',
    meal_type: 'भोजन प्रकार',
    total_amount_collected: 'ग्राहक से एकत्र की जाने वाली कुल राशि:',
    cod_badge: 'सीओडी (नकद)',
    paid_online_badge: 'ऑनलाइन भुगतान',
    picked_up_btn: '>> पार्सल उठा लिया',
    delivered_btn: '-> डिलीवर किया गया',
    enter_delivery_otp: 'ग्राहक डिलीवरी ओटीपी दर्ज करें',
    verify_otp_modal_title: 'डिलीवरी ओटीपी सत्यापन',
    customer_otp_hint: 'खाना सौंपने से पहले ग्राहक से 4 अंकों का ओटीपी कोड मांगें।',
    confirm_and_complete: 'ओटीपी सत्यापित करें और डिलीवरी पूरी करें',
    invalid_otp: 'अमान्य ओटीपी कोड।',
    sealed_container_title: 'सील बंद स्वच्छ भोजन पैकेजिंग',
    sealed_container_desc: 'डिस्पोजेबल प्लास्टिक कंटेनर में सुरक्षित डिलीवरी। खाली डिब्बे वापस लेने की जरूरत नहीं।',
    available_orders_radar: 'पास के रसोई ऑर्डर (5 किमी के भीतर)',
    no_active_orders: 'फिलहाल कोई सक्रिय ऑर्डर नहीं है।',
    accept_order_btn: 'डिलीवरी स्वीकार करें',
    radar_searching: '5 किमी के दायरे में खोज रहा है...',
    new_order_alert: 'नया ऑर्डर अलर्ट!',
    km_away: 'किमी दूर',
    rider_verified: '4.8 / सत्यापित',
    account_details: 'खाता विवरण:',
    account_details_sub: 'फोन, ईमेल, वाहन',
    documents: 'दस्तावेज़:',
    driving_license: 'ड्राइविंग लाइसेंस',
    rc_book: 'आरसी बुक',
    preferences: 'प्राथमिकताएं:',
    preferences_sub: 'भाषा, आवाज अलर्ट',
    bank_details: 'बैंक विवरण:',
    bank_details_sub: 'भुगतान विधियां, यूपीआई',
    support: 'सहायता:',
    contact_us: 'संपर्क करें,',
    sos_button: 'एसओएस बटन',
    terms_of_service: 'सेवा की शर्तें',
    logout: 'लॉग आउट',
    sos_emergency_modal: 'आपातकालीन एसओएस चेतावनी',
    sos_warning: 'एसओएस दबाने से आपका लाइव स्थान सहायता टीम को भेजा जाएगा।',
    trigger_sos: 'एसओएस सिग्नल भेजें',
    cancel: 'रद्द करें',
    save_changes: 'सुरक्षित करें',
    total_earned: 'कुल कमाई',
    per_day_earned: 'आज (दिन)',
    per_week_earned: 'इस सप्ताह',
    per_month_earned: 'इस महीने',
    per_order_earned: 'इस ऑर्डर की कमाई',
    confidential_title: 'गोपनीय कमाई सुरक्षित है',
    confidential_sub: 'देखने के लिए फिंगरप्रिंट या पिन दर्ज करें',
    unlock_earnings_btn: 'कमाई अनलॉक करें',
    biometric_btn: 'फिंगरप्रिंट / फेस आईडी',
    or_enter_pin: 'या 4-अंकीय पिन दर्ज करें',
    pin_placeholder: '4-अंकीय पिन (डिफ़ॉल्ट 1234)',
    unlock_now: 'सत्यापित करें और अनलॉक करें',
    lock_again: 'छुपाएं और लॉक करें',
    withdraw_instantly: 'तुरंत यूपीआई पर निकालें',
    deliveries_completed: 'पूर्ण किए गए ऑर्डर',
    recent_earnings: 'हाल की ऑर्डर कमाई',
    transfer_success: 'यूपीआई पर सफलतापूर्वक स्थानांतरित!'
  },

  // ==========================================
  // TELUGU (తెలుగు)
  // ==========================================
  te: {
    app_title: 'హోమ్‌పాట్ డెలివరీ',
    home: 'హోమ్',
    payout: 'మొత్తం సంపాదన',
    profile: 'ప్రొఫైల్',
    terms_privacy_notice: 'నిబంధనలు మరియు గోప్యతా విధానానికి లోబడి ఉంటుంది.',
    start_your_journey: 'మీ ప్రయాణాన్ని ప్రారంభించండి',
    deliver_fresh_earn: 'తాజా ఇంటి భోజనాన్ని అందించి సంపాదించండి',
    daily_earnings_badge: 'రోజుకు ₹500+ సంపాదన',
    live_tracking_badge: '5 కి.మీ రాడార్',
    login_btn: 'లాగిన్',
    join_us_btn: 'సైన్ అప్',
    enter_details_title: 'మీ వివరాలను నమోదు చేయండి',
    verify_phone_title: 'ఫోన్ మరియు ఇమెయిల్ ధృవీకరించండి',
    full_name_label: 'పూర్తి పేరు',
    full_name_placeholder: 'కుమార్ వి.',
    email_id_label: 'ఇమెయిల్ ఐడి',
    email_id_placeholder: 'kumar.delivery@gmail.com',
    phone_number_label: 'ఫోన్ నంబర్',
    phone_placeholder: '+91 9876543210',
    accept_terms: 'నేను నిబంధనలను అంగీకరిస్తున్నాను',
    send_otp_btn: 'OTP పంపండి',
    enter_6_digit_otp: '6 అంకెల OTP నమోదు చేయండి',
    resend_otp: 'మళ్ళీ OTP పంపండి',
    verify_proceed_btn: 'ధృవీకరించి కొనసాగండి',
    sending_code: 'కోడ్ పంపుతోంది...',
    rider_kyc_title: 'వాహనం మరియు బ్యాంక్ వివరాలు',
    vehicle_info_title: 'వాహన వివరాలు',
    vehicle_type: 'వాహన రకం',
    electric_scooter: 'ఎలక్ట్రిక్ స్కూటర్',
    petrol_bike: 'పెట్రోల్ బైక్',
    bicycle: 'సైకిల్',
    vehicle_number: 'వాహన రిజిస్ట్రేషన్ నంబర్',
    driving_license_no: 'డ్రైవింగ్ లైసెన్స్ నంబర్',
    operating_city: 'ఆపరేటింగ్ నగరం',
    bank_payout_title: 'బ్యాంక్ మరియు UPI వివరాలు',
    account_holder_name: 'ఖాతాదారుని పేరు',
    bank_account_number: 'బ్యాంక్ ఖాతా సంఖ్య',
    ifsc_code: 'IFSC కోడ్',
    upi_id_label: 'UPI ఐడి',
    complete_onboarding_btn: 'పూర్తి చేసి ఆన్‌లైన్‌కి వెళ్ళండి',
    in_progress_tab: 'ప్రస్తుత ఆర్డర్',
    history_tab: 'చరిత్ర',
    order_status_active: 'యాక్టివ్ డెలివరీ',
    est_delivery_time: 'సమయం: 20-25 నిమిషాలు',
    confirmed: 'ధృవీకరించబడింది',
    cooking: 'వంట జరుగుతోంది',
    out_for_delivery: 'డెలివరీకి బయలుదేరింది',
    delivered: 'డెలివరీ చేయబడింది',
    cancelled: 'రద్దు చేయబడింది',
    kitchen_details: 'వంటగది వివరాలు',
    pickup_address: 'పికప్ చిరునామా',
    drop_off_address: 'డ్రాప్ చిరునామా',
    view_order_items: 'ఆర్డర్ వస్తువులు',
    meal_type: 'భోజన రకం',
    total_amount_collected: 'సేకరించవలసిన మొత్తం:',
    cod_badge: 'నగదు (COD)',
    paid_online_badge: 'ఆన్‌లైన్ చెల్లింపు',
    picked_up_btn: '>> పికప్ చేసాను',
    delivered_btn: '-> డెలివరీ పూర్తయింది',
    enter_delivery_otp: 'కస్టమర్ OTP నమోదు చేయండి',
    verify_otp_modal_title: 'డెలివరీ OTP ధృవీకరణ',
    customer_otp_hint: 'ఆహారాన్ని అందించే ముందు కస్టమర్‌ను 4 అంకెల OTP అడగండి.',
    confirm_and_complete: 'OTP ధృవీకరించి పూర్తి చేయండి',
    invalid_otp: 'చెల్లని OTP.',
    sealed_container_title: 'సీల్ చేయబడిన సురక్షిత ఆహార ప్యాకేజింగ్',
    sealed_container_desc: 'డిస్పోజబుల్ ప్లాస్టిక్ కంటైనర్‌లో డెలివరీ. ఖాళీ డబ్బా తిరిగి తీసుకోవలసిన అవసరం లేదు.',
    available_orders_radar: 'సమీప వంటగది ఆర్డర్‌లు (5 కి.మీ)',
    no_active_orders: 'ప్రస్తుతం ఆర్డర్‌లు లేవు.',
    accept_order_btn: 'డెలివరీ స్వీకరించండి',
    radar_searching: '5 కి.మీ పరిధిలో శోధిస్తోంది...',
    new_order_alert: 'కొత్త ఆర్డర్ వచ్చింది!',
    km_away: 'కి.మీ దూరంలో',
    rider_verified: '4.8 / ధృవీకరించబడింది',
    account_details: 'ఖాతా వివరాలు:',
    account_details_sub: 'ఫోన్, ఇమెయిల్, వాహనం',
    documents: 'పత్రాలు:',
    driving_license: 'డ్రైవింగ్ లైసెన్స్',
    rc_book: 'RC బుక్',
    preferences: 'ప్రాధాన్యతలు:',
    preferences_sub: 'భాష, శబ్దాలు',
    bank_details: 'బ్యాంక్ వివరాలు:',
    bank_details_sub: 'చెల్లింపు పద్ధతులు, UPI',
    support: 'మద్దతు:',
    contact_us: 'మమ్మల్ని సంప్రదించండి,',
    sos_button: 'SOS బటన్',
    terms_of_service: 'సేవా నిబంధనలు',
    logout: 'లాగ్ అవుట్',
    sos_emergency_modal: 'అత్యవసర SOS హెచ్చరిక',
    sos_warning: 'SOS బటన్ నొక్కడం వలన మీ ప్రత్యక్ష స్థానం వెంటనే షేర్ చేయబడుతుంది.',
    trigger_sos: 'SOS పంపండి',
    cancel: 'రద్దు చేయండి',
    save_changes: 'సేవ్ చేయండి',
    total_earned: 'మొత్తం సంపాదన',
    per_day_earned: 'ఈరోజు (రోజు)',
    per_week_earned: 'ఈ వారం',
    per_month_earned: 'ఈ నెల',
    per_order_earned: 'ఈ ఆర్డర్ సంపాదన',
    confidential_title: 'గోప్యమైన సంపాదన లాక్ చేయబడింది',
    confidential_sub: 'చూడటానికి వేలిముద్ర లేదా పిన్ ఉపయోగించండి',
    unlock_earnings_btn: 'సంపాదన అన్‌లాక్ చేయండి',
    biometric_btn: 'ఫింగర్‌ప్రింట్ / ఫేస్ ఐడి',
    or_enter_pin: 'లేదా 4-అంకెల పిన్ నమోదు చేయండి',
    pin_placeholder: '4-అంకెల పిన్ (డిఫాల్ట్ 1234)',
    unlock_now: 'ధృవీకరించి తెరవండి',
    lock_again: 'దాచడానికి లాక్ చేయండి',
    withdraw_instantly: 'వెంటనే UPI కి బదిలీ చేయండి',
    deliveries_completed: 'పూర్తయిన ఆర్డర్‌లు',
    recent_earnings: 'ఇటీవలి ఆర్డర్ సంపాదనలు',
    transfer_success: 'UPI కి విజయవంతంగా బదిలీ చేయబడింది!'
  },

  // ==========================================
  // KANNADA (ಕನ್ನಡ)
  // ==========================================
  kn: {
    app_title: 'ಹೋಮ್‌ಪಾಟ್ ಡೆಲಿವರಿ',
    home: 'ಮುಖಪುಟ',
    payout: 'ಒಟ್ಟು ಗಳಿಕೆ',
    profile: 'ಪ್ರೊಫೈಲ್',
    terms_privacy_notice: 'ನಿಯಮಗಳು ಮತ್ತು ಗೌಪ್ಯತಾ ನೀತಿಗೆ ಒಳಪಟ್ಟಿರುತ್ತದೆ.',
    start_your_journey: 'ನಿಮ್ಮ ಪ್ರಯಾಣವನ್ನು ಪ್ರಾರಂಭಿಸಿ',
    deliver_fresh_earn: 'ಮನೆಯ ಊಟ ತಲುಪಿಸಿ ಮತ್ತು ಗಳಿಸಿ',
    daily_earnings_badge: 'ದಿನಕ್ಕೆ ₹500+ ಗಳಿಕೆ',
    live_tracking_badge: '5 ಕಿ.ಮೀ ರಾಡಾರ್',
    login_btn: 'ಲಾಗಿನ್',
    join_us_btn: 'ಸೈನ್ ಅಪ್',
    enter_details_title: 'ನಿಮ್ಮ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ',
    verify_phone_title: 'ಫೋನ್ ಮತ್ತು ಇಮೇಲ್ ಪರಿಶೀಲಿಸಿ',
    full_name_label: 'ಪೂರ್ಣ ಹೆಸರು',
    full_name_placeholder: 'ಕುಮಾರ್ ವಿ.',
    email_id_label: 'ಇಮೇಲ್ ಐಡಿ',
    email_id_placeholder: 'kumar.delivery@gmail.com',
    phone_number_label: 'ಫೋನ್ ಸಂಖ್ಯೆ',
    phone_placeholder: '+91 9876543210',
    accept_terms: 'ನಾನು ನಿಯಮಗಳನ್ನು ಒಪ್ಪುತ್ತೇನೆ',
    send_otp_btn: 'OTP ಕಳುಹಿಸಿ',
    enter_6_digit_otp: '6 ಅಂಕಿಯ OTP ನಮೂದಿಸಿ',
    resend_otp: 'ಮತ್ತೆ OTP ಕಳುಹಿಸಿ',
    verify_proceed_btn: 'ಪರಿಶೀಲಿಸಿ ಮುಂದುವರಿಯಿರಿ',
    sending_code: 'ಕೋಡ್ ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ...',
    rider_kyc_title: 'ವಾಹನ ಮತ್ತು ಬ್ಯಾಂಕ್ ವಿವರಗಳು',
    vehicle_info_title: 'ವಾಹನ ವಿವರಗಳು',
    vehicle_type: 'ವಾಹನದ ಪ್ರಕಾರ',
    electric_scooter: 'ಎಲೆಕ್ಟ್ರಿಕ್ ಸ್ಕೂಟರ್',
    petrol_bike: 'ಪೆಟ್ರೋಲ್ ಬೈಕ್',
    bicycle: 'ಸೈಕಲ್',
    vehicle_number: 'ವಾಹನ ನೋಂದಣಿ ಸಂಖ್ಯೆ',
    driving_license_no: 'ಚಾಲನಾ ಪರವಾನಗಿ ಸಂಖ್ಯೆ',
    operating_city: 'ಕಾರ್ಯನಿರ್ವಹಿಸುವ ನಗರ',
    bank_payout_title: 'ಬ್ಯಾಂಕ್ ಮತ್ತು UPI ವಿವರಗಳು',
    account_holder_name: 'ಖಾತೆದಾರರ ಹೆಸರು',
    bank_account_number: 'ಬ್ಯಾಂಕ್ ಖಾತೆ ಸಂಖ್ಯೆ',
    ifsc_code: 'IFSC ಕೋಡ್',
    upi_id_label: 'UPI ಐಡಿ',
    complete_onboarding_btn: 'ಪೂರ್ಣಗೊಳಿಸಿ ಆನ್‌ಲೈನ್‌ಗೆ ಹೋಗಿ',
    in_progress_tab: 'ಪ್ರಸ್ತುತ ಆರ್ಡರ್',
    history_tab: 'ಇತಿಹಾಸ',
    order_status_active: 'ಸಕ್ರಿಯ ಡೆಲಿವರಿ',
    est_delivery_time: 'ಸಮಯ: 20-25 ನಿಮಿಷ',
    confirmed: 'ದೃಢಪಡಿಸಲಾಗಿದೆ',
    cooking: 'ತಯಾರಾಗುತ್ತಿದೆ',
    out_for_delivery: 'ಡೆಲಿವರಿಗೆ ಹೊರಟಿದೆ',
    delivered: 'ತಲುಪಿಸಲಾಗಿದೆ',
    cancelled: 'ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ',
    kitchen_details: 'ಅಡುಗೆಮನೆ ವಿವರಗಳು',
    pickup_address: 'ಪಿಕಪ್ ವಿಳಾಸ',
    drop_off_address: 'ಡೆಲಿವರಿ ವಿಳಾಸ',
    view_order_items: 'ಆರ್ಡರ್ ಐಟಂಗಳು',
    meal_type: 'ಊಟದ ಪ್ರಕಾರ',
    total_amount_collected: 'ಸಂಗ್ರಹಿಸಬೇಕಾದ ಒಟ್ಟು ಮೊತ್ತ:',
    cod_badge: 'ನಗದು (COD)',
    paid_online_badge: 'ಆನ್‌ಲೈನ್ ಪಾವತಿ',
    picked_up_btn: '>> ಪಿಕಪ್ ಮಾಡಲಾಗಿದೆ',
    delivered_btn: '-> ತಲುಪಿಸಲಾಗಿದೆ',
    enter_delivery_otp: 'ಗ್ರಾಹಕರ OTP ನಮೂದಿಸಿ',
    verify_otp_modal_title: 'ಡೆಲಿವರಿ OTP ಪರಿಶೀಲನೆ',
    customer_otp_hint: 'ಆಹಾರವನ್ನು ನೀಡುವ ಮೊದಲು 4 ಅಂಕಿಯ OTP ಕೇಳಿ.',
    confirm_and_complete: 'OTP ಪರಿಶೀಲಿಸಿ ಮುಕ್ತಾಯಗೊಳಿಸಿ',
    invalid_otp: 'ತಪ್ಪಾದ OTP.',
    sealed_container_title: 'ಸೀಲ್ ಮಾಡಿದ ಸುರಕ್ಷಿತ ಆಹಾರ ಪ್ಯಾಕೇಜಿಂಗ್',
    sealed_container_desc: 'ಡಿಸ್ಪೋಸಬಲ್ ಪ್ಲಾಸ್ಟಿಕ್ ಕಂಟೇನರ್‌ನಲ್ಲಿ ತಲುಪಿಸಲಾಗುತ್ತದೆ. ಖಾಲಿ ಡಬ್ಬಾ ಮರಳಿ ಪಡೆಯುವ ಅಗತ್ಯವಿಲ್ಲ.',
    available_orders_radar: 'ಹತ್ತಿರದ ಅಡುಗೆಮನೆ ಆರ್ಡರ್‌ಗಳು (5 ಕಿ.ಮೀ)',
    no_active_orders: 'ಯಾವುದೇ ಸಕ್ರಿಯ ಆರ್ಡರ್‌ಗಳಿಲ್ಲ.',
    accept_order_btn: 'ಡೆಲಿವರಿ ಸ್ವೀಕರಿಸಿ',
    radar_searching: '5 ಕಿ.ಮೀ ವ್ಯಾಪ್ತಿಯಲ್ಲಿ ಹುಡುಕುತ್ತಿದೆ...',
    new_order_alert: 'ಹೊಸ ಆರ್ಡರ್ ಬಂದಿದೆ!',
    km_away: 'ಕಿ.ಮೀ ದೂರದಲ್ಲಿ',
    rider_verified: '4.8 / ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    account_details: 'ಖಾತೆ ವಿವರಗಳು:',
    account_details_sub: 'ಫೋನ್, ಇಮೇಲ್, ವಾಹನ',
    documents: 'ದಾಖಲೆಗಳು:',
    driving_license: 'ಚಾಲನಾ ಪರವಾನಗಿ',
    rc_book: 'RC ಬುಕ್',
    preferences: 'ಆದ್ಯತೆಗಳು:',
    preferences_sub: 'ಭಾಷೆ, ಧ್ವನಿ ಎಚ್ಚರಿಕೆಗಳು',
    bank_details: 'ಬ್ಯಾಂಕ್ ವಿವರಗಳು:',
    bank_details_sub: 'ಪಾವತಿ ವಿಧಾನಗಳು, UPI',
    support: 'ಬೆಂಬಲ:',
    contact_us: 'ಸಂಪರ್ಕಿಸಿ,',
    sos_button: 'SOS ಬಟನ್',
    terms_of_service: 'ಸೇವಾ ನಿಯಮಗಳು',
    logout: 'ಲಾಗ್ ಔಟ್',
    sos_emergency_modal: 'ತುರ್ತು SOS ಎಚ್ಚರಿಕೆ',
    sos_warning: 'SOS ಒತ್ತಿದರೆ ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ತಕ್ಷಣ ಹಂಚಿಕೊಳ್ಳಲಾಗುತ್ತದೆ.',
    trigger_sos: 'SOS ಕಳುಹಿಸಿ',
    cancel: 'ರದ್ದುಮಾಡಿ',
    save_changes: 'ಉಳಿಸಿ',
    total_earned: 'ಒಟ್ಟು ಗಳಿಕೆ',
    per_day_earned: 'ಇಂದು (ದಿನ)',
    per_week_earned: 'ಈ ವಾರ',
    per_month_earned: 'ಈ ತಿಂಗಳು',
    per_order_earned: 'ಈ ಆರ್ಡರ್ ಗಳಿಕೆ',
    confidential_title: 'ಗೌಪ್ಯ ಗಳಿಕೆ ಲಾಕ್ ಆಗಿದೆ',
    confidential_sub: 'ನೋಡಲು ಫಿಂಗರ್‌ಪ್ರಿಂಟ್ ಅಥವಾ ಪಿನ್ ಬಳಸಿ',
    unlock_earnings_btn: 'ಗಳಿಕೆ ಅನ್‌ಲಾಕ್ ಮಾಡಿ',
    biometric_btn: 'ಫಿಂಗರ್‌ಪ್ರಿಂಟ್ / ಫೇಸ್ ಐಡಿ',
    or_enter_pin: 'ಅಥವಾ 4-ಅಂಕಿಯ ಪಿನ್ ನಮೂದಿಸಿ',
    pin_placeholder: '4-ಅಂಕಿಯ ಪಿನ್ (ಡೀಫಾಲ್ಟ್ 1234)',
    unlock_now: 'ಪರಿಶೀಲಿಸಿ ಅನ್‌ಲಾಕ್ ಮಾಡಿ',
    lock_again: 'ಮರೆಮಾಡಲು ಲಾಕ್ ಮಾಡಿ',
    withdraw_instantly: 'ತಕ್ಷಣ UPI ಗೆ ವರ್ಗಾಯಿಸಿ',
    deliveries_completed: 'ಪೂರ್ಣಗೊಂಡ ಆರ್ಡರ್‌ಗಳು',
    recent_earnings: 'ಇತ್ತೀಚಿನ ಆರ್ಡರ್ ಗಳಿಕೆಗಳು',
    transfer_success: 'UPI ಗೆ ಯಶಸ್ವಿಯಾಗಿ ವರ್ಗಾಯಿಸಲಾಗಿದೆ!'
  },

  // ==========================================
  // MALAYALAM (മലയാളം)
  // ==========================================
  ml: {
    app_title: 'ഹോംപോട്ട് ഡെലിവറി',
    home: 'ഹോം',
    payout: 'ആകെ വരുമാനം',
    profile: 'പ്രൊഫൈൽ',
    terms_privacy_notice: 'നിബന്ധനകൾക്കും സ്വകാര്യതാ നയത്തിനും വിധേയമാണ്.',
    start_your_journey: 'നിങ്ങളുടെ യാത്ര ആരംഭിക്കുക',
    deliver_fresh_earn: 'ചൂടുള്ള വീട്ടിലെ ഭക്ഷണം എത്തിച്ച് വരുമാനം നേടുക',
    daily_earnings_badge: 'പ്രതിദിനം ₹500+ വരുമാനം',
    live_tracking_badge: '5 കി.മീ റഡാർ',
    login_btn: 'ലോഗിൻ',
    join_us_btn: 'സൈൻ അപ്പ്',
    enter_details_title: 'നിങ്ങളുടെ വിവരങ്ങൾ നൽകുക',
    verify_phone_title: 'ഫോണും ഇമെയിലും പരിശോധിക്കുക',
    full_name_label: 'പൂർണ്ണ പേര്',
    full_name_placeholder: 'കുമാർ വി.',
    email_id_label: 'ഇമെയിൽ വിലാസം',
    email_id_placeholder: 'kumar.delivery@gmail.com',
    phone_number_label: 'ഫോൺ നമ്പർ',
    phone_placeholder: '+91 9876543210',
    accept_terms: 'ഞാൻ നിബന്ധനകൾ അംഗീകരിക്കുന്നു',
    send_otp_btn: 'OTP അയക്കുക',
    enter_6_digit_otp: '6 അക്ക OTP നൽകുക',
    resend_otp: 'വീണ്ടും OTP അയക്കുക',
    verify_proceed_btn: 'പരിശോധിച്ച് തുടരുക',
    sending_code: 'കോഡ് അയക്കുന്നു...',
    rider_kyc_title: 'വാഹനവും ബാങ്ക് വിവരങ്ങളും',
    vehicle_info_title: 'വാഹന വിവരങ്ങൾ',
    vehicle_type: 'വാഹന തരം',
    electric_scooter: 'ഇലക്ട്രിക് സ്കൂട്ടർ',
    petrol_bike: 'പെട്രോൾ ബൈക്ക്',
    bicycle: 'സൈക്കിൾ',
    vehicle_number: 'വാഹന രജിസ്ട്രേഷൻ നമ്പർ',
    driving_license_no: 'ഡ്രൈവിംഗ് ലൈസൻസ് നമ്പർ',
    operating_city: 'പ്രവർത്തന നഗരം',
    bank_payout_title: 'ബാങ്ക്, UPI വിവരങ്ങൾ',
    account_holder_name: 'അക്കൗണ്ട് ഉടമയുടെ പേര്',
    bank_account_number: 'ബാങ്ക് അക്കൗണ്ട് നമ്പർ',
    ifsc_code: 'IFSC കോഡ്',
    upi_id_label: 'UPI ഐഡി',
    complete_onboarding_btn: 'പൂർത്തിയാക്കി ഓൺലൈനിൽ പോകുക',
    in_progress_tab: 'സജീവമായ ഓർഡർ',
    history_tab: 'ചരിത്രം',
    order_status_active: 'സജീവ ഡെലിവറി',
    est_delivery_time: 'സമയം: 20-25 മിനിറ്റ്',
    confirmed: 'സ്ഥിരീകരിച്ചു',
    cooking: 'തയ്യാറാക്കുന്നു',
    out_for_delivery: 'ഡെലിവറിക്കായി തിരിച്ചു',
    delivered: 'ഡെലിവർ ചെയ്തു',
    cancelled: 'റദ്ദാക്കി',
    kitchen_details: 'അടുക്കള വിവരങ്ങൾ',
    pickup_address: 'പിക്കപ്പ് വിലാസം',
    drop_off_address: 'ഡെലിവറി വിലാസം',
    view_order_items: 'ഭക്ഷണ ഇനങ്ങൾ',
    meal_type: 'ഭക്ഷണ തരം',
    total_amount_collected: 'വാങ്ങേണ്ട ആകെ തുക:',
    cod_badge: 'പണം (COD)',
    paid_online_badge: 'ഓൺലൈൻ പേയ്മെന്റ്',
    picked_up_btn: '>> പിക്കപ്പ് ചെയ്തു',
    delivered_btn: '-> ഡെലിവർ ചെയ്തു',
    enter_delivery_otp: 'കസ്റ്റമർ OTP നൽകുക',
    verify_otp_modal_title: 'ഡെലിവറി OTP പരിശോധന',
    customer_otp_hint: 'ഭക്ഷണം നൽകുന്നതിന് മുൻപ് 4 അക്ക OTP ചോദിക്കുക.',
    confirm_and_complete: 'OTP പരിശോധിച്ച് പൂർത്തിയാക്കുക',
    invalid_otp: 'തെറ്റായ OTP.',
    sealed_container_title: 'സീൽ ചെയ്ത സുരക്ഷിത പാക്കേജിംഗ്',
    sealed_container_desc: 'ഡിസ്പോസിബിൾ പ്ലാസ്റ്റിക് പാത്രത്തിൽ സുരക്ഷിതമായി നൽകുന്നു. ഒഴിഞ്ഞ പാത്രം തിരികെ വാങ്ങേണ്ടതില്ല.',
    available_orders_radar: 'അടുത്തുള്ള അടുക്കള ഓർഡറുകൾ (5 കി.മീ)',
    no_active_orders: 'നിലവിൽ ഓർഡറുകൾ ഒന്നുമില്ല.',
    accept_order_btn: 'ഡെലിവറി സ്വീകരിക്കുക',
    radar_searching: '5 കി.മീ പരിധിയിൽ തിരയുന്നു...',
    new_order_alert: 'പുതിയ ഓർഡർ എത്തിയിരിക്കുന്നു!',
    km_away: 'കി.മീ അകലെ',
    rider_verified: '4.8 / സ്ഥിരീകരിച്ചു',
    account_details: 'അക്കൗണ്ട് വിവരങ്ങൾ:',
    account_details_sub: 'ഫോൺ, ഇമെയിൽ, വാഹനം',
    documents: 'രേഖകൾ:',
    driving_license: 'ഡ്രൈവിംഗ് ലൈസൻസ്',
    rc_book: 'ആർ.സി ബുക്ക്',
    preferences: 'മുൻഗണനകൾ:',
    preferences_sub: 'ഭാഷ, ശബ്ദ അലേർട്ടുകൾ',
    bank_details: 'ബാങ്ക് വിവരങ്ങൾ:',
    bank_details_sub: 'പേയ്‌മെന്റ് രീതികൾ, UPI',
    support: 'സഹായം:',
    contact_us: 'ബന്ധപ്പെടുക,',
    sos_button: 'SOS ബട്ടൺ',
    terms_of_service: 'സേവന നിബന്ധനകൾ',
    logout: 'ലോഗ് ഔട്ട്',
    sos_emergency_modal: 'അടിയന്തര SOS മുന്നറിയിപ്പ്',
    sos_warning: 'SOS അമർത്തിയാൽ നിങ്ങളുടെ ലൊക്കേഷൻ ഉടൻ തന്നെ സഹായ സംഘത്തിന് കൈമാറും.',
    trigger_sos: 'SOS അയക്കുക',
    cancel: 'റദ്ദാക്കുക',
    save_changes: 'സംരക്ഷിക്കുക',
    total_earned: 'ആകെ വരുമാനം',
    per_day_earned: 'ഇന്ന് (ദിവസം)',
    per_week_earned: 'ഈ ആഴ്ച',
    per_month_earned: 'ഈ മാസം',
    per_order_earned: 'ഈ ഓർഡർ വരുമാനം',
    confidential_title: 'രഹസ്യ വരുമാനം ലോക്ക് ചെയ്തു',
    confidential_sub: 'കാണാൻ വിരലടയാളം അല്ലെങ്കിൽ പിൻ നൽകുക',
    unlock_earnings_btn: 'വരുമാനം അൺലോക്ക് ചെയ്യുക',
    biometric_btn: 'ഫിംഗർപ്രിന്റ് / ഫെയ്സ് ഐഡി',
    or_enter_pin: 'അല്ലെങ്കിൽ 4-അക്ക പിൻ നൽകുക',
    pin_placeholder: '4-അക്ക പിൻ (ഡിഫോൾട്ട് 1234)',
    unlock_now: 'പരിശോധിച്ച് അൺലോക്ക് ചെയ്യുക',
    lock_again: 'മറയ്ക്കാൻ ലോക്ക് ചെയ്യുക',
    withdraw_instantly: 'ഉടൻ UPI-ലേക്ക് മാറ്റുക',
    deliveries_completed: 'പൂർത്തിയായ ഓർഡറുകൾ',
    recent_earnings: 'സമീപകാല ഓർഡർ വരുമാനങ്ങൾ',
    transfer_success: 'തുക UPI-ലേക്ക് വിജയകരമായി കൈമാറി!'
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [currentLang, setCurrentLang] = useState(() => {
    return localStorage.getItem('homepot_rider_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('homepot_rider_lang', currentLang);
    document.documentElement.lang = currentLang;
  }, [currentLang]);

  const t = (key) => {
    if (TRANSLATIONS[currentLang] && TRANSLATIONS[currentLang][key]) {
      return TRANSLATIONS[currentLang][key];
    }
    if (TRANSLATIONS['en'] && TRANSLATIONS['en'][key]) {
      return TRANSLATIONS['en'][key];
    }
    return key;
  };

  const changeLanguage = (langCode) => {
    if (TRANSLATIONS[langCode]) {
      setCurrentLang(langCode);
    }
  };

  return (
    <LanguageContext.Provider value={{ currentLang, changeLanguage, t, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
