import React, { createContext, useContext, useState, useEffect } from 'react';

export const LANGUAGES = [
  { code: 'en', label: 'English', name: 'English', flag: '🇬🇧' },
  { code: 'ta', label: 'தமிழ்', name: 'Tamil', flag: '🇮🇳' },
  { code: 'hi', label: 'हिंदी', name: 'Hindi', flag: '🇮🇳' },
  { code: 'te', label: 'తెలుగు', name: 'Telugu', flag: '🇮🇳' },
  { code: 'kn', label: 'ಕನ್ನಡ', name: 'Kannada', flag: '🇮🇳' },
  { code: 'ml', label: 'മലയാളം', name: 'Malayalam', flag: '🇮🇳' }
];

export const TRANSLATIONS = {
  // ==========================================
  // ENGLISH (en)
  // ==========================================
  en: {
    // Branding & Navigation
    app_title: 'HomePot Delivery',
    home: 'Home',
    payout: 'Payout',
    profile: 'Profile',
    terms_privacy_notice: 'Terms and Privacy under the terms and Privacy list below.',

    // Welcome Page (Image 3)
    start_your_journey: 'Start Your Journey',
    deliver_fresh_earn: 'Deliver Fresh Home Food & Earn',
    daily_earnings_badge: '₹500+ daily earnings',
    live_tracking_badge: 'Live Tracking',
    login_btn: 'LOGIN',
    join_us_btn: 'JOIN US / SIGN UP',

    // Step 2A & 2B Auth (Image 4)
    step_2a_title: 'Step 2A: Enter Details',
    step_2b_title: 'Step 2B: Verify Phone',
    full_name_label: 'Full Name',
    full_name_placeholder: 'Kumar V.',
    email_id_label: 'Email ID',
    email_id_placeholder: 'kumar.delivery@gmail.com',
    phone_number_label: 'Phone Number',
    phone_placeholder: '+91 9876543210',
    accept_terms: 'I accept terms',
    send_otp_btn: 'SEND OTP',
    enter_6_digit_otp: 'Enter 6-digit OTP sent to',
    resend_otp: 'Resend OTP',
    verify_proceed_btn: 'VERIFY & PROCEED',
    sending_code: 'Sending verification code...',

    // Step 2C KYC & Onboarding
    step_2c_title: 'Step 2C: Rider Details & Payout Setup',
    vehicle_info_title: 'Registered Vehicle Details',
    vehicle_type: 'Vehicle Type',
    electric_scooter: 'Electric Scooter',
    petrol_bike: 'Petrol Bike / Motorcycle',
    bicycle: 'Bicycle / EV Cycle',
    vehicle_number: 'Vehicle Registration Number',
    driving_license_no: 'Driving License Number',
    operating_city: 'Operating City / Hub',
    bank_payout_title: 'Bank & UPI Settlement Details',
    account_holder_name: 'Account Holder Name',
    bank_account_number: 'Bank Account Number',
    ifsc_code: 'IFSC Code',
    upi_id_label: 'Primary UPI ID (GPay / PhonePe / Paytm)',
    complete_onboarding_btn: 'Complete Setup & Go Online',

    // Order Radar (Image 2 & Image 5)
    in_progress_tab: 'In Progress',
    history_tab: 'History',
    time_remaining: 'Time Remaining',
    confirmed: 'Confirmed',
    cooking: 'Cooking',
    out_for_delivery: 'Out for Delivery',
    delivered: 'DELIVERED',
    cancelled: 'CANCELLED',
    kitchen_details: 'Kitchen details',
    pickup_address: 'Pickup address',
    drop_off_address: 'Drop-off address',
    view_order_items: 'View order items',
    meal_type: 'Meal Type',
    total_amount_collected: 'Total amount to be collected:',
    cod_badge: 'COD',
    paid_online_badge: 'PAID ONLINE',
    picked_up_btn: '>> Picked Up',
    delivered_btn: '-> Delivered',
    enter_delivery_otp: 'Enter Customer Delivery OTP',
    verify_otp_modal_title: 'Verify Customer Delivery OTP',
    customer_otp_hint: 'Ask the customer for the 4-digit code shown on their HomePot app before handing over food.',
    confirm_and_complete: 'Verify OTP & Complete Delivery',
    invalid_otp: 'Invalid OTP code. Please verify with customer.',
    eco_tiffin_bonus: 'Eco-Tiffin Return Bonus',
    tiffin_return_available: '+₹20 Tiffin Return Bonus Available!',
    tiffin_collected: 'Collected empty clean tiffin from customer',
    available_orders_radar: 'Nearby Kitchen Orders (Within 5 km)',
    no_active_orders: 'No orders in progress right now. Nearby kitchen requests will appear below!',
    accept_order_btn: 'Accept Delivery',
    radar_searching: 'Scanning 5 km radius around you...',
    new_order_alert: 'New Home Order Alert!',
    km_away: 'km away',

    // Profile (Image 1)
    rider_verified: '4.8 / Verified',
    account_details: 'Account Details:',
    account_details_sub: 'Phone, Email, Registered Vehicle',
    documents: 'Documents:',
    driving_license: 'Driving License',
    rc_book: 'RC',
    preferences: 'Preferences:',
    preferences_sub: 'Language, Sound & Voice Alerts',
    bank_details: 'Bank Details:',
    bank_details_sub: 'Payment methods, Bank Account, UPI ID',
    support: 'Support:',
    contact_us: 'Contact Us,',
    sos_button: 'SOS Button',
    terms_of_service: 'Terms of Service',
    logout: 'Logout',
    sos_emergency_modal: 'Emergency SOS Alert',
    sos_warning: 'Pressing SOS will immediately broadcast your live GPS coordinates to emergency support and local authorities.',
    trigger_sos: 'CONFIRM & SEND SOS SIGNAL',
    cancel: 'Cancel',
    save_changes: 'Save Changes',

    // Payout
    todays_earnings: "Today's Earnings",
    total_payout_balance: 'Available Payout Balance',
    withdraw_instantly: 'Withdraw Instantly via UPI',
    deliveries_completed: 'Deliveries Completed',
    tiffin_bonuses_earned: 'Tiffin Swap Bonuses',
    customer_tips: 'Customer Tips (100% to you)',
    recent_payouts: 'Recent Payouts & History',
    transfer_success: 'Successfully transferred to UPI!'
  },

  // ==========================================
  // TAMIL (தமிழ்)
  // ==========================================
  ta: {
    app_title: 'ஹோம்பாட் டெலிவரி',
    home: 'முகப்பு',
    payout: 'வருமானம்',
    profile: 'சுயவிவரம்',
    terms_privacy_notice: 'விதிமுறைகள் மற்றும் தனியுரிமைக் கொள்கைக்கு உட்பட்டது.',

    start_your_journey: 'உங்கள் பயணத்தை தொடங்குங்கள்',
    deliver_fresh_earn: 'சூடான வீட்டு உணவை வழங்கி சம்பாதிக்கவும்',
    daily_earnings_badge: 'தினமும் ₹500+ வருமானம்',
    live_tracking_badge: 'நேரடி கண்காணிப்பு',
    login_btn: 'உள்நுழைக (LOGIN)',
    join_us_btn: 'புதிய ரைடர் பதிவு (SIGN UP)',

    step_2a_title: 'படி 2A: உங்கள் விவரங்களை உள்ளிடவும்',
    step_2b_title: 'படி 2B: தொலைபேசி சரிபார்ப்பு',
    full_name_label: 'முழு பெயர்',
    full_name_placeholder: 'குமார் வி.',
    email_id_label: 'மின்னஞ்சல் முகவரி',
    email_id_placeholder: 'kumar.delivery@gmail.com',
    phone_number_label: 'கைபேசி எண்',
    phone_placeholder: '+91 9876543210',
    accept_terms: 'விதிமுறைகளை ஏற்கிறேன்',
    send_otp_btn: 'OTP குறியீடு அனுப்பு',
    enter_6_digit_otp: 'அனுப்பப்பட்ட 6-இலக்க OTP ஐ உள்ளிடவும்:',
    resend_otp: 'மறுபடி அனுப்பு',
    verify_proceed_btn: 'சரிபார்த்து தொடரவும்',
    sending_code: 'சரிபார்ப்புக் குறியீடு அனுப்பப்படுகிறது...',

    step_2c_title: 'படி 2C: வாகன & வங்கி விவரங்கள்',
    vehicle_info_title: 'பதிவு செய்யப்பட்ட வாகன விவரங்கள்',
    vehicle_type: 'வாகன வகை',
    electric_scooter: 'எலக்ட்ரிக் ஸ்கூட்டர்',
    petrol_bike: 'பெட்ரோல் பைக் / மோட்டார் சைக்கிள்',
    bicycle: 'சைக்கிள்',
    vehicle_number: 'வாகன பதிவு எண்',
    driving_license_no: 'ஓட்டுநர் உரிம எண் (DL)',
    operating_city: 'பணிபுரியும் நகரம்',
    bank_payout_title: 'வங்கி & UPI பணப்பட்டுவாடா',
    account_holder_name: 'கணக்கு வைத்திருப்பவர் பெயர்',
    bank_account_number: 'வங்கி கணக்கு எண்',
    ifsc_code: 'IFSC குறியீடு',
    upi_id_label: 'முக்கிய UPI முகவரி (GPay / PhonePe)',
    complete_onboarding_btn: 'அமைத்து ஆன்லைனுக்கு செல்லவும்',

    in_progress_tab: 'செயலில் உள்ளவை',
    history_tab: 'வரலாறு',
    time_remaining: 'மீதமுள்ள நேரம்',
    confirmed: 'உறுதியானது',
    cooking: 'சமைக்கப்படுகிறது',
    out_for_delivery: 'டெலிவரிக்கு செல்கிறது',
    delivered: 'வழங்கப்பட்டது (DELIVERED)',
    cancelled: 'ரத்து செய்யப்பட்டது',
    kitchen_details: 'சமையலறை விவரங்கள்',
    pickup_address: 'உணவு எடுக்கும் இடம்',
    drop_off_address: 'வாடிக்கையாளர் முகவரி',
    view_order_items: 'உணவுப் பொருட்கள்',
    meal_type: 'உணவு வகை',
    total_amount_collected: 'வசூலிக்க வேண்டிய தொகை:',
    cod_badge: 'ரொக்கம் (COD)',
    paid_online_badge: 'ஆன்லைனில் செலுத்தப்பட்டது',
    picked_up_btn: '>> உணவு எடுக்கப்பட்டது (Picked Up)',
    delivered_btn: '-> உணவு வழங்கப்பட்டது (Delivered)',
    enter_delivery_otp: 'வாடிக்கையாளர் டெலிவரி OTP உள்ளிடவும்',
    verify_otp_modal_title: 'வாடிக்கையாளர் OTP சரிபார்ப்பு',
    customer_otp_hint: 'உணவை வழங்குவதற்கு முன் வாடிக்கையாளர் செயலியில் உள்ள 4 இலக்க OTP ஐ கேட்டுப் பெறவும்.',
    confirm_and_complete: 'OTP சரிபார்த்து டெலிவரியை முடிக்கவும்',
    invalid_otp: 'தவறான OTP. வாடிக்கையாளரிடம் சரிபார்க்கவும்.',
    eco_tiffin_bonus: 'பாத்திரம் திரும்பப்பெறும் போனஸ்',
    tiffin_return_available: '+₹20 பாத்திரம் திரும்பப்பெறும் போனஸ் உண்டு!',
    tiffin_collected: 'வாடிக்கையாளரிடம் பழைய பாத்திரம் பெறப்பட்டது',
    available_orders_radar: 'அருகிலுள்ள ஆர்டர்கள் (5 கி.மீ எல்லைக்குள்)',
    no_active_orders: 'தற்போது செயலில் ஆர்டர்கள் இல்லை. 5 கி.மீ அருகிலுள்ள சமையலறை ஆர்டர்கள் கீழே தோன்றும்!',
    accept_order_btn: 'ஆர்டரை ஏற்கவும்',
    radar_searching: 'உங்களைச் சுற்றியுள்ள 5 கி.மீ பகுதியை ஸ்கேன் செய்கிறது...',
    new_order_alert: 'புதிய வீட்டு உணவு ஆர்டர் வந்துள்ளது!',
    km_away: 'கி.மீ தூரத்தில்',

    rider_verified: '4.8 / சரிபார்க்கப்பட்டது',
    account_details: 'கணக்கு விவரங்கள்:',
    account_details_sub: 'தொலைபேசி, மின்னஞ்சல், வாகனம்',
    documents: 'ஆவணங்கள்:',
    driving_license: 'ஓட்டுநர் உரிமம்',
    rc_book: 'RC புத்தகம்',
    preferences: 'அமைப்புகள்:',
    preferences_sub: 'மொழி, ஒலி விழிப்பூட்டல்கள்',
    bank_details: 'வங்கி விவரங்கள்:',
    bank_details_sub: 'வங்கி கணக்கு, UPI முகவரி',
    support: 'உதவி & ஆதரவு:',
    contact_us: 'தொடர்பு கொள்ள,',
    sos_button: 'SOS அவசர உதவி',
    terms_of_service: 'சேவை விதிமுறைகள்',
    logout: 'வெளியேறு (Logout)',
    sos_emergency_modal: 'அவசர SOS உதவி எச்சரிக்கை',
    sos_warning: 'SOS பொத்தானை அழுத்தினால் உங்கள் நேரடி GPS இருப்பிடம் உடனடியாக அவசர உதவி மையத்திற்கு பகிரப்படும்.',
    trigger_sos: 'உறுதி செய்து SOS அனுப்பவும்',
    cancel: 'ரத்து',
    save_changes: 'சேமிக்கவும்',

    todays_earnings: 'இன்றைய வருமானம்',
    total_payout_balance: 'எடுக்கக்கூடிய இருப்பு',
    withdraw_instantly: 'UPI வழியாக உடனே எடுக்கவும்',
    deliveries_completed: 'டெலிவரிகள் முடிந்தது',
    tiffin_bonuses_earned: 'பாத்திர பரிமாற்ற போனஸ்',
    customer_tips: 'வாடிக்கையாளர் அன்பளிப்பு (100% உங்களுக்கு)',
    recent_payouts: 'சமீபத்திய பணப்பரிவர்த்தனைகள்',
    transfer_success: 'UPI கணக்கிற்கு உடனடியாக அனுப்பப்பட்டது!'
  },

  // ==========================================
  // HINDI (हिंदी)
  // ==========================================
  hi: {
    app_title: 'होमपॉट डिलीवरी',
    home: 'होम',
    payout: 'कमाई',
    profile: 'प्रोफाइल',
    terms_privacy_notice: 'नियम और गोपनीयता सूची के अंतर्गत।',
    start_your_journey: 'अपनी यात्रा शुरू करें',
    deliver_fresh_earn: 'घर का ताजा भोजन पहुंचाएं और कमाएं',
    daily_earnings_badge: 'रोजाना ₹500+ कमाई',
    live_tracking_badge: 'लाइव ट्रैकिंग',
    login_btn: 'लॉग इन (LOGIN)',
    join_us_btn: 'शामिल हों (SIGN UP)',
    step_2a_title: 'चरण 2A: विवरण दर्ज करें',
    step_2b_title: 'चरण 2B: फोन सत्यापित करें',
    full_name_label: 'पूरा नाम',
    full_name_placeholder: 'कुमार वी.',
    email_id_label: 'ईमेल आईडी',
    phone_number_label: 'फोन नंबर',
    accept_terms: 'नियम स्वीकार हैं',
    send_otp_btn: 'OTP भेजें',
    enter_6_digit_otp: 'भेजा गया 6-अंकीय OTP दर्ज करें:',
    resend_otp: 'दोबारा भेजें',
    verify_proceed_btn: 'सत्यापित करें और आगे बढ़ें',
    step_2c_title: 'चरण 2C: राइडर और बैंक विवरण',
    vehicle_info_title: 'पंजीकृत वाहन विवरण',
    vehicle_type: 'वाहन का प्रकार',
    electric_scooter: 'इलेक्ट्रिक स्कूटर',
    petrol_bike: 'पेट्रोल बाइक',
    bicycle: 'साइकिल',
    vehicle_number: 'वाहन नंबर',
    driving_license_no: 'ड्राइविंग लाइसेंस नंबर',
    bank_payout_title: 'बैंक और UPI भुगतान विवरण',
    account_holder_name: 'खाताधारक का नाम',
    bank_account_number: 'बैंक खाता संख्या',
    ifsc_code: 'IFSC कोड',
    upi_id_label: 'प्राथमिक UPI आईडी (GPay / PhonePe)',
    complete_onboarding_btn: 'सेटअप पूरा करें और ऑनलाइन जाएं',
    in_progress_tab: 'चालू ऑर्डर',
    history_tab: 'इतिहास',
    time_remaining: 'शेष समय',
    confirmed: 'पुष्ट',
    cooking: 'पक रहा है',
    out_for_delivery: 'डिलीवरी के लिए रवाना',
    delivered: 'डिलीवर किया गया',
    kitchen_details: 'रसोई विवरण',
    pickup_address: 'पिकअप पता',
    drop_off_address: 'डिलीवरी पता',
    view_order_items: 'ऑर्डर सामग्री',
    meal_type: 'भोजन प्रकार',
    total_amount_collected: 'संग्रहित की जाने वाली कुल राशि:',
    cod_badge: 'नकद (COD)',
    paid_online_badge: 'ऑनलाइन भुगतान',
    picked_up_btn: '>> पिकअप किया (Picked Up)',
    delivered_btn: '-> डिलीवर किया (Delivered)',
    enter_delivery_otp: 'ग्राहक का डिलीवरी OTP दर्ज करें',
    verify_otp_modal_title: 'डिलीवरी OTP सत्यापन',
    customer_otp_hint: 'भोजन सौंपने से पहले ग्राहक ऐप में दिख रहा 4-अंकीय OTP दर्ज करें।',
    confirm_and_complete: 'OTP सत्यापित करें और पूरा करें',
    invalid_otp: 'अमान्य OTP। कृपया ग्राहक से जांचें।',
    eco_tiffin_bonus: 'टिफिन वापसी बोनस',
    tiffin_return_available: '+₹20 टिफिन वापसी बोनस उपलब्ध है!',
    available_orders_radar: 'पास के ऑर्डर्स (5 किमी के भीतर)',
    no_active_orders: 'वर्तमान में कोई चालू ऑर्डर नहीं है। 5 किमी के भीतर ऑर्डर्स नीचे दिखेंगे!',
    accept_order_btn: 'ऑर्डर स्वीकार करें',
    radar_searching: 'आपके आसपास 5 किमी क्षेत्र को स्कैन कर रहा है...',
    new_order_alert: 'नया होम फूड ऑर्डर आया है!',
    km_away: 'किमी दूर',
    rider_verified: '4.8 / सत्यापित',
    account_details: 'खाता विवरण:',
    documents: 'दस्तावेज:',
    preferences: 'प्राथमिकताएं:',
    bank_details: 'बैंक विवरण:',
    support: 'सहायता:',
    sos_button: 'SOS बटन',
    terms_of_service: 'सेवा की शर्तें',
    logout: 'लॉग आउट',
    sos_emergency_modal: 'आपातकालीन SOS अलर्ट',
    trigger_sos: 'पुष्टि करें और SOS भेजें',
    cancel: 'रद्द करें',
    todays_earnings: 'आज की कमाई',
    total_payout_balance: 'उपलब्ध शेष राशि',
    withdraw_instantly: 'UPI से तुरंत निकालें',
    transfer_success: 'पैसे सीधे UPI में ट्रांसफर हो गए!'
  },

  // ==========================================
  // TELUGU (తెలుగు)
  // ==========================================
  te: {
    app_title: 'హోమ్‌పాట్ డెలివరీ',
    home: 'హోమ్',
    payout: 'ఆదాయం',
    profile: 'ప్రొఫైల్',
    terms_privacy_notice: 'నిబంధనలు మరియు గోప్యతా జాబితా క్రింద.',
    start_your_journey: 'మీ ప్రయాణాన్ని ప్రారంభించండి',
    deliver_fresh_earn: 'తాజా ఇంటి ఆహారాన్ని డెలివరీ చేయండి & సంపాదించండి',
    daily_earnings_badge: 'రోజుకు ₹500+ సంపాదన',
    live_tracking_badge: 'లైవ్ ట్రాకింగ్',
    login_btn: 'లాగిన్ (LOGIN)',
    join_us_btn: 'చేరండి (SIGN UP)',
    step_2a_title: 'దశ 2A: వివరాలను నమోదు చేయండి',
    step_2b_title: 'దశ 2B: ఫోన్ ధృవీకరించండి',
    full_name_label: 'పూర్తి పేరు',
    email_id_label: 'ఈమెయిల్ ఐడీ',
    phone_number_label: 'ఫోన్ నంబర్',
    accept_terms: 'నిబంధనలను అంగీకరిస్తున్నాను',
    send_otp_btn: 'OTP పంపండి',
    enter_6_digit_otp: 'పంపిన 6-అంకెల OTP నమోదు చేయండి:',
    resend_otp: 'మళ్లీ పంపు',
    verify_proceed_btn: 'ధృవీకరించి కొనసాగండి',
    step_2c_title: 'దశ 2C: రైడర్ & బ్యాంకు వివరాలు',
    vehicle_info_title: 'నమోదైన వాహన వివరాలు',
    vehicle_type: 'వాహనం రకం',
    electric_scooter: 'ఎలక్ట్రిక్ స్కూటర్',
    petrol_bike: 'పెట్రోల్ బైక్',
    bicycle: 'సైకిల్',
    vehicle_number: 'వాహనం నంబర్',
    driving_license_no: 'డ్రైవింగ్ లైసెన్స్ సంఖ్య',
    bank_payout_title: 'బ్యాంకు & UPI చెల్లింపు వివరాలు',
    account_holder_name: 'ఖాతాదారుని పేరు',
    bank_account_number: 'బ్యాంకు ఖాతా సంఖ్య',
    ifsc_code: 'IFSC కోడ్',
    upi_id_label: 'ప్రధాన UPI ఐడీ (GPay / PhonePe)',
    complete_onboarding_btn: 'సెటప్ పూర్తి చేసి ఆన్‌లైన్‌కు వెళ్లండి',
    in_progress_tab: 'పురోగతిలో ఉంది',
    history_tab: 'చరిత్ర',
    time_remaining: 'మిగిలిన సమయం',
    confirmed: 'ధృవీకరించబడింది',
    cooking: 'వండుతున్నారు',
    out_for_delivery: 'డెలివరీకి బయలుదేరింది',
    delivered: 'డెలివరీ చేయబడింది',
    kitchen_details: 'వంటగది వివరాలు',
    pickup_address: 'పికప్ చిరునామా',
    drop_off_address: 'కస్టమర్ చిరునామా',
    view_order_items: 'ఆర్డర్ వస్తువులు',
    meal_type: 'భోజన రకం',
    total_amount_collected: 'వసూలు చేయాల్సిన మొత్తం:',
    cod_badge: 'నగదు (COD)',
    paid_online_badge: 'ఆన్‌లైన్ చెల్లింపు',
    picked_up_btn: '>> పికప్ చేసాము (Picked Up)',
    delivered_btn: '-> డెలివరీ చేసాము (Delivered)',
    enter_delivery_otp: 'కస్టమర్ డెలివరీ OTP నమోదు చేయండి',
    verify_otp_modal_title: 'డెలివరీ OTP ధృవీకరణ',
    customer_otp_hint: 'ఆహారాన్ని ఇచ్చే ముందు కస్టమర్ యాప్‌లో కనిపించే 4 అంకెల OTP ని నమోదు చేయండి.',
    confirm_and_complete: 'ధృవీకరించి డెలివరీ పూర్తి చేయండి',
    invalid_otp: 'తప్పు OTP. దయచేసి కస్టమర్‌తో తనిఖీ చేయండి.',
    eco_tiffin_bonus: 'టిఫిన్ రిటర్న్ బోనస్',
    tiffin_return_available: '+₹20 టిఫిన్ రిటర్న్ బోనస్ అందుబాటులో ఉంది!',
    available_orders_radar: 'సమీప ఆర్డర్లు (5 కిమీ పరిధిలో)',
    no_active_orders: 'ప్రస్తుతం యాక్టివ్ ఆర్డర్లు లేవు. 5 కిమీ పరిధిలోని ఆర్డర్లు క్రింద కనిపిస్తాయి!',
    accept_order_btn: 'ఆర్డర్ స్వీకరించండి',
    radar_searching: 'మీ చుట్టూ 5 కిమీ ప్రాంతాన్ని స్కాన్ చేస్తోంది...',
    new_order_alert: 'కొత్త ఇంటి ఆహార ఆర్డర్ వచ్చింది!',
    km_away: 'కిమీ దూరంలో',
    rider_verified: '4.8 / ధృవీకరించబడింది',
    account_details: 'ఖాతా వివరాలు:',
    documents: 'పత్రాలు:',
    preferences: 'ప్రాధాన్యతలు:',
    bank_details: 'బ్యాంకు వివరాలు:',
    support: 'మద్దతు:',
    sos_button: 'SOS బటన్',
    terms_of_service: 'సేవా నిబంధనలు',
    logout: 'లాగ్ అవుట్',
    sos_emergency_modal: 'అత్యవసర SOS హెచ్చరిక',
    trigger_sos: 'నిర్ధారించి SOS పంపండి',
    cancel: 'రద్దు',
    todays_earnings: 'నేటి ఆదాయం',
    total_payout_balance: 'అందుబాటులో ఉన్న నిల్వ',
    withdraw_instantly: 'UPI ద్వారా వెంటనే విత్‌డ్రా చేయండి',
    transfer_success: 'సొమ్ము నేరుగా UPI ఖాతాకు బదిలీ చేయబడింది!'
  },

  // ==========================================
  // KANNADA (ಕನ್ನಡ)
  // ==========================================
  kn: {
    app_title: 'ಹೋಮ್‌ಪಾಟ್ ಡೆಲಿವರಿ',
    home: 'ಮುಖಪುಟ',
    payout: 'ಗಳಿಕೆ',
    profile: 'ಪ್ರೊಫೈಲ್',
    terms_privacy_notice: 'ನಿಯಮಗಳು ಮತ್ತು ಗೌಪ್ಯತೆ ನೀತಿಗೆ ಒಳಪಟ್ಟಿದೆ.',
    start_your_journey: 'ನಿಮ್ಮ ಪ್ರಯಾಣವನ್ನು ಪ್ರಾರಂಭಿಸಿ',
    deliver_fresh_earn: 'ಮನೆಯ ರುಚಿಯಾದ ಆಹಾರವನ್ನು ತಲುಪಿಸಿ ಮತ್ತು ಗಳಿಸಿ',
    daily_earnings_badge: 'ದಿನಕ್ಕೆ ₹500+ ಗಳಿಕೆ',
    live_tracking_badge: 'ಲೈವ್ ಟ್ರ್ಯಾಕಿಂಗ್',
    login_btn: 'ಲಾಗಿನ್ (LOGIN)',
    join_us_btn: 'ಸೇರಿ (SIGN UP)',
    step_2a_title: 'ಹಂತ 2A: ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ',
    step_2b_title: 'ಹಂತ 2B: ಫೋನ್ ಪರಿಶೀಲಿಸಿ',
    full_name_label: 'ಪೂರ್ಣ ಹೆಸರು',
    email_id_label: 'ಇಮೇಲ್ ಐಡಿ',
    phone_number_label: 'ಫೋನ್ ಸಂಖ್ಯೆ',
    accept_terms: 'ನಿಯಮಗಳನ್ನು ಒಪ್ಪುತ್ತೇನೆ',
    send_otp_btn: 'OTP ಕಳುಹಿಸಿ',
    enter_6_digit_otp: 'ಕಳುಹಿಸಲಾದ 6-ಅಂಕಿಯ OTP ನಮೂದಿಸಿ:',
    resend_otp: 'ಮತ್ತೆ ಕಳುಹಿಸಿ',
    verify_proceed_btn: 'ಪರಿಶೀಲಿಸಿ ಮುಂದುವರಿಯಿರಿ',
    step_2c_title: 'ಹಂತ 2C: ರೈಡರ್ ಮತ್ತು ಬ್ಯಾಂಕ್ ವಿವರಗಳು',
    vehicle_info_title: 'ನೋಂದಾಯಿತ ವಾಹನ ವಿವರಗಳು',
    vehicle_type: 'ವಾಹನದ ವಿಧ',
    electric_scooter: 'ಎಲೆಕ್ಟ್ರಿಕ್ ಸ್ಕೂಟರ್',
    petrol_bike: 'ಪೆಟ್ರೋಲ್ ಬೈಕ್',
    bicycle: 'ಸೈಕಲ್',
    vehicle_number: 'ವಾಹನ ಸಂಖ್ಯೆ',
    driving_license_no: 'ಚಾಲನಾ ಪರವಾನಗಿ ಸಂಖ್ಯೆ',
    bank_payout_title: 'ಬ್ಯಾಂಕ್ ಮತ್ತು UPI ಪಾವತಿ ವಿವರಗಳು',
    account_holder_name: 'ಖಾತೆದಾರರ ಹೆಸರು',
    bank_account_number: 'ಬ್ಯಾಂಕ್ ಖಾತೆ ಸಂಖ್ಯೆ',
    ifsc_code: 'IFSC ಕೋಡ್',
    upi_id_label: 'ಪ್ರಾಥಮಿಕ UPI ಐಡಿ (GPay / PhonePe)',
    complete_onboarding_btn: 'ಸೆಟಪ್ ಪೂರ್ಣಗೊಳಿಸಿ ಆನ್‌ಲೈನ್‌ಗೆ ಹೋಗಿ',
    in_progress_tab: 'ಪ್ರಗತಿಯಲ್ಲಿದೆ',
    history_tab: 'ಇತಿಹಾಸ',
    time_remaining: 'ಉಳಿದ ಸಮಯ',
    confirmed: 'ದೃಢೀಕರಿಸಲಾಗಿದೆ',
    cooking: 'ತಯಾರಾಗುತ್ತಿದೆ',
    out_for_delivery: 'ಡೆಲಿವರಿಗೆ ಹೊರಟಿದೆ',
    delivered: 'ತಲುಪಿಸಲಾಗಿದೆ',
    kitchen_details: 'ಅಡುಗೆಮನೆ ವಿವರಗಳು',
    pickup_address: 'ಪಿಕಪ್ ವಿಳಾಸ',
    drop_off_address: 'ಗ್ರಾಹಕರ ವಿಳಾಸ',
    view_order_items: 'ಆರ್ಡರ್ ವಸ್ತುಗಳು',
    meal_type: 'ಊಟದ ವಿಧ',
    total_amount_collected: 'ಸಂಗ್ರಹಿಸಬೇಕಾದ ಒಟ್ಟು ಮೊತ್ತ:',
    cod_badge: 'ನಗದು (COD)',
    paid_online_badge: 'ಆನ್‌ಲೈನ್ ಪಾವತಿ',
    picked_up_btn: '>> ಪಿಕಪ್ ಮಾಡಲಾಗಿದೆ (Picked Up)',
    delivered_btn: '-> ತಲುಪಿಸಲಾಗಿದೆ (Delivered)',
    enter_delivery_otp: 'ಗ್ರಾಹಕರ ಡೆಲಿವರಿ OTP ನಮೂದಿಸಿ',
    verify_otp_modal_title: 'ಡೆಲಿವರಿ OTP ಪರಿಶೀಲನೆ',
    customer_otp_hint: 'ಆಹಾರವನ್ನು ನೀಡುವ ಮೊದಲು ಗ್ರಾಹಕರ ಆ್ಯಪ್‌ನಲ್ಲಿರುವ 4 ಅಂಕಿಯ OTP ಪರಿಶೀಲಿಸಿ.',
    confirm_and_complete: 'ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಪೂರ್ಣಗೊಳಿಸಿ',
    invalid_otp: 'ತಪ್ಪಾದ OTP. ಗ್ರಾಹಕರೊಂದಿಗೆ ಪರಿಶೀಲಿಸಿ.',
    eco_tiffin_bonus: 'ಟಿಫಿನ್ ರಿಟರ್ನ್ ಬೋನಸ್',
    tiffin_return_available: '+₹20 ಟಿಫಿನ್ ರಿಟರ್ನ್ ಬೋನಸ್ ಲಭ್ಯವಿದೆ!',
    available_orders_radar: 'ಸಮೀಪದ ಆರ್ಡರ್‌ಗಳು (5 ಕಿಮೀ ಒಳಗೆ)',
    no_active_orders: 'ಪ್ರಸ್ತುತ ಯಾವುದೇ ಸಕ್ರಿಯ ಆರ್ಡರ್‌ಗಳಿಲ್ಲ. 5 ಕಿಮೀ ಒಳಗಿನ ಆರ್ಡರ್‌ಗಳು ಕೆಳಗೆ ಕಾಣಿಸುತ್ತವೆ!',
    accept_order_btn: 'ಆರ್ಡರ್ ಸ್ವೀಕರಿಸಿ',
    radar_searching: 'ನಿಮ್ಮ ಸುತ್ತಲಿನ 5 ಕಿಮೀ ವ್ಯಾಪ್ತಿಯನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    new_order_alert: 'ಹೊಸ ಮನೆ ಆಹಾರದ ಆರ್ಡರ್ ಬಂದಿದೆ!',
    km_away: 'ಕಿಮೀ ದೂರದಲ್ಲಿದೆ',
    rider_verified: '4.8 / ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    account_details: 'ಖಾತೆ ವಿವರಗಳು:',
    documents: 'ದಾಖಲೆಗಳು:',
    preferences: 'ಆದ್ಯತೆಗಳು:',
    bank_details: 'ಬ್ಯಾಂಕ್ ವಿವರಗಳು:',
    support: 'ಬೆಂಬಲ:',
    sos_button: 'SOS ಬಟನ್',
    terms_of_service: 'ಸೇವಾ ನಿಯಮಗಳು',
    logout: 'ಲಾಗ್ ಔಟ್',
    sos_emergency_modal: 'ತುರ್ತು SOS ಎಚ್ಚರಿಕೆ',
    trigger_sos: 'ದೃಢೀಕರಿಸಿ ಮತ್ತು SOS ಕಳುಹಿಸಿ',
    cancel: 'ರದ್ದು',
    todays_earnings: 'ಇಂದಿನ ಗಳಿಕೆ',
    total_payout_balance: 'ಲಭ್ಯವಿರುವ ಬಾಕಿ ಮೊತ್ತ',
    withdraw_instantly: 'UPI ಮೂಲಕ ತಕ್ಷಣ ಹಿಂಪಡೆಯಿರಿ',
    transfer_success: 'ಹಣವನ್ನು ನೇರವಾಗಿ UPI ಖಾತೆಗೆ ವರ್ಗಾಯಿಸಲಾಗಿದೆ!'
  },

  // ==========================================
  // MALAYALAM (മലയാളം)
  // ==========================================
  ml: {
    app_title: 'ഹോംപോട്ട് ഡെലിവറി',
    home: 'ഹോം',
    payout: 'വരുമാനം',
    profile: 'പ്രൊഫൈൽ',
    terms_privacy_notice: 'വ്യവസ്ഥകൾക്കും സ്വകാര്യതാ നയത്തിനും വിധേയമാണ്.',
    start_your_journey: 'നിങ്ങളുടെ യാത്ര ആരംഭിക്കുക',
    deliver_fresh_earn: 'നാടൻ ഭക്ഷണം എത്തിക്കൂ • സമ്പാദിക്കൂ',
    daily_earnings_badge: 'ദിവസേന ₹500+ വരുമാനം',
    live_tracking_badge: 'തത്സമയ ട്രാക്കിംഗ്',
    login_btn: 'ലോഗിൻ (LOGIN)',
    join_us_btn: 'രജിസ്റ്റർ ചെയ്യുക (SIGN UP)',
    step_2a_title: 'ഘട്ടം 2A: വിവരങ്ങൾ നൽകുക',
    step_2b_title: 'ഘട്ടം 2B: ഫോൺ പരിശോധിക്കുക',
    full_name_label: 'പൂർണ്ണമായ പേര്',
    email_id_label: 'ഇമെയിൽ വിലാസം',
    phone_number_label: 'ഫോൺ നമ്പർ',
    accept_terms: 'വ്യവസ്ഥകൾ അംഗീകരിക്കുന്നു',
    send_otp_btn: 'OTP അയയ്ക്കുക',
    enter_6_digit_otp: 'ലഭിച്ച 6-അക്ക OTP നൽകുക:',
    resend_otp: 'വീണ്ടും അയയ്ക്കുക',
    verify_proceed_btn: 'പരിശോധിച്ച് തുടരുക',
    step_2c_title: 'ഘട്ടം 2C: റൈഡർ & ബാങ്ക് വിവരങ്ങൾ',
    vehicle_info_title: 'വാഹന വിവരങ്ങൾ',
    vehicle_type: 'വാഹന തരം',
    electric_scooter: 'ഇലക്ട്രിക് സ്കൂട്ടർ',
    petrol_bike: 'പെട്രോൾ ബൈക്ക്',
    bicycle: 'സൈക്കിൾ',
    vehicle_number: 'വാഹന നമ്പർ',
    driving_license_no: 'ഡ്രൈവിംഗ് ലൈസൻസ് നമ്പർ',
    bank_payout_title: 'ബാങ്ക് & UPI പേയ്‌മെന്റ് വിവരങ്ങൾ',
    account_holder_name: 'അക്കൗണ്ട് ഉടമയുടെ പേര്',
    bank_account_number: 'ബാങ്ക് അക്കൗണ്ട് നമ്പർ',
    ifsc_code: 'IFSC കോഡ്',
    upi_id_label: 'പ്രധാന UPI ഐഡി (GPay / PhonePe)',
    complete_onboarding_btn: 'പൂർത്തിയാക്കി ഓൺലൈനിൽ പോകുക',
    in_progress_tab: 'നിലവിലുള്ളവ',
    history_tab: 'ചരിത്രം',
    time_remaining: 'ബാക്കി സമയം',
    confirmed: 'സ്ഥിരീകരിച്ചു',
    cooking: 'പാചകം ചെയ്യുന്നു',
    out_for_delivery: 'ഡെലിവറിക്കായി തിരിച്ചു',
    delivered: 'ഡെലിവർ ചെയ്തു',
    kitchen_details: 'അടുക്കള വിവരങ്ങൾ',
    pickup_address: 'ഭക്ഷണം എടുക്കുന്ന സ്ഥലം',
    drop_off_address: 'കസ്റ്റമർ വിലാസം',
    view_order_items: 'ഭക്ഷണ വിഭവങ്ങൾ',
    meal_type: 'ഭക്ഷണ തരം',
    total_amount_collected: 'പിരിക്കേണ്ട ആകെ തുക:',
    cod_badge: 'പണം (COD)',
    paid_online_badge: 'ഓൺലൈൻ പേയ്‌മെന്റ്',
    picked_up_btn: '>> ഭക്ഷണം എടുത്തു (Picked Up)',
    delivered_btn: '-> ഭക്ഷണം എത്തിച്ചു (Delivered)',
    enter_delivery_otp: 'കസ്റ്റമറുടെ ഡെലിവറി OTP നൽകുക',
    verify_otp_modal_title: 'ഡെലിവറി OTP സ്ഥിരീകരണം',
    customer_otp_hint: 'ഭക്ഷണം കൈമാറുന്നതിന് മുൻപ് കസ്റ്റമറുടെ ആപ്പിലെ 4 അക്ക OTP നൽകുക.',
    confirm_and_complete: 'OTP പരിശോധിച്ച് പൂർത്തിയാക്കുക',
    invalid_otp: 'തെറ്റായ OTP. കസ്റ്റമറുമായി പരിശോധിക്കുക.',
    eco_tiffin_bonus: 'ടിഫിൻ റിട്ടേൺ ബോണസ്',
    tiffin_return_available: '+₹20 ടിഫിൻ റിട്ടേൺ ബോണസ് ലഭ്യമാണ്!',
    available_orders_radar: 'സമീപത്തുള്ള ഓർഡറുകൾ (5 കി.മീ ചുറ്റളവിൽ)',
    no_active_orders: 'നിലവിൽ ഓർഡറുകളൊന്നുമില്ല. 5 കി.മീ പരിധിയിലുള്ളവ താഴെ കാണാം!',
    accept_order_btn: 'ഓർഡർ സ്വീകരിക്കുക',
    radar_searching: '5 കി.മീ പരിധി തിരയുന്നു...',
    new_order_alert: 'പുതിയ നാടൻ ഭക്ഷണ ഓർഡർ എത്തി!',
    km_away: 'കി.മീ അകലെ',
    rider_verified: '4.8 / പരിശോധിച്ചുറപ്പിച്ചു',
    account_details: 'അക്കൗണ്ട് വിവരങ്ങൾ:',
    documents: 'രേഖകൾ:',
    preferences: 'മുൻഗണനകൾ:',
    bank_details: 'ബാങ്ക് വിവരങ്ങൾ:',
    support: 'സഹായം:',
    sos_button: 'SOS ബട്ടൺ',
    terms_of_service: 'സേവന വ്യവസ്ഥകൾ',
    logout: 'ലോഗ് ഔട്ട്',
    sos_emergency_modal: 'അടിയന്തര SOS മുന്നറിയിപ്പ്',
    trigger_sos: 'സ്ഥിരീകരിച്ച് SOS അയയ്ക്കുക',
    cancel: 'റദ്ദാക്കുക',
    todays_earnings: 'ഇന്നത്തെ വരുമാനം',
    total_payout_balance: 'ലഭ്യമായ ബാലൻസ്',
    withdraw_instantly: 'UPI വഴി തത്സമയം പിൻവലിക്കുക',
    transfer_success: 'തുക നേരിട്ട് UPI അക്കൗണ്ടിലേക്ക് മാറ്റി!'
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [currentLang, setCurrentLang] = useState(() => {
    return localStorage.getItem('homepot_delivery_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('homepot_delivery_lang', currentLang);
    document.documentElement.lang = currentLang;
  }, [currentLang]);

  const t = (key) => {
    if (TRANSLATIONS[currentLang] && TRANSLATIONS[currentLang][key]) {
      return TRANSLATIONS[currentLang][key];
    }
    if (TRANSLATIONS['en'] && TRANSLATIONS['en'][key]) {
      return TRANSLATIONS['en'][key];
    }
    return key;
  };

  return (
    <LanguageContext.Provider value={{ currentLang, setCurrentLang, t, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
